In [2]:
from pathlib import Path
from gears import PertData
import pandas as pd
import scanpy as sc
from tqdm import tqdm

In [3]:
ref_dir = Path('/Users/djemec/data/jepa/reference_data')
data_dir = Path('/Users/djemec/data/jepa/v0_6')
pert_dir = data_dir / 'pert_embd'
training_dir = data_dir / 'training'
pretraining_dir = data_dir / 'pretraining'

pert_temp = data_dir / 'pert_tmp'

In [4]:
key_ds =  {'k562e':ref_dir / 'k562e'}
datasets= {
    'k562e_raw': ref_dir / 'raw_k562e' / 'K562_essential_raw_singlecell_01.h5ad',
    'rep1e':ref_dir /'rep1e'/'rpe1_raw_singlecell_01.h5ad',
    'k562gw':ref_dir /'k562gw'/'perturb_processed.h5ad',
    'adamson':ref_dir /'adamson'/'AdamsonWeissman2016_GSM2406681_10X010.h5ad',
    'norman':ref_dir /'norman'/'NormanWeissman2019_filtered.h5ad',
    'sciplex':ref_dir /'sciplex'/'SrivatsanTrapnell2020_sciplex3.h5ad', 
}

In [11]:
splits= ['train','val','test']
n_genes = 16384
count_normalize_target = 1e4

## Review Key dataset and extract genes we have counts for

In [32]:
ds_key = 'k562e_raw'
ds_adata = sc.read_h5ad(datasets[ds_key], backed='r')
var_df = ds_adata.var
var_df.head()

,gene_name,chr,start,end,class,strand,length,in_matrix,mean,std,cv,fano
gene_id,,,,,,,,,,,,
ENSG00000237491,LINC01409,chr1,778747,810065,gene_version10,+,31318,True,0.137594,0.380048,2.762105,1.049733
ENSG00000228794,LINC01128,chr1,825138,868202,gene_version9,+,43064,True,0.256720,0.520162,2.026184,1.053944
ENSG00000188976,NOC2L,chr1,944203,959309,gene_version11,-,15106,True,1.975144,1.707837,0.864665,1.476706
ENSG00000187961,KLHL17,chr1,960584,965719,gene_version14,+,5135,True,0.119593,0.353702,2.957540,1.046089
ENSG00000188290,HES4,chr1,998962,1000172,gene_version10,-,1210,True,0.249577,0.561933,2.251540,1.265214

In [33]:
all_genes = var_df['gene_name'].to_dict()
len(all_genes.keys())

8563

## Get Genes from other datasets

#### rep1e

In [34]:
ds_key = 'rep1e'
ds_adata = sc.read_h5ad(datasets[ds_key], backed='r')
var_df = ds_adata.var
var_df.head()

,gene_name,chr,start,end,class,strand,length,in_matrix,mean,std,cv,fano
gene_id,,,,,,,,,,,,
ENSG00000188976,NOC2L,chr1,944203,959309,gene_version11,-,15106,True,0.997140,1.149519,1.152816,1.325185
ENSG00000187583,PLEKHN1,chr1,966482,975865,gene_version11,+,9383,True,0.131328,0.377933,2.877783,1.087609
ENSG00000188290,HES4,chr1,998962,1000172,gene_version10,-,1210,True,0.732129,1.526109,2.084482,3.181148
ENSG00000187608,ISG15,chr1,1001138,1014540,gene_version10,+,13402,True,0.455956,1.260789,2.765152,3.486272
ENSG00000188157,AGRN,chr1,1020120,1056118,gene_version15,+,35998,True,0.346108,0.648378,1.873341,1.214633

In [35]:
new_genes = var_df['gene_name'].to_dict()
len(new_genes.keys())

8749

In [36]:
# check conflicts
conflicts = {k: (all_genes[k], v) for k, v in new_genes.items() if k in all_genes and all_genes[k] != v}
conflicts

{}

In [37]:
all_genes = {**new_genes, **all_genes}
len(all_genes)

10086

#### k562gw

In [43]:
ds_key = 'k562gw'
ds_adata = sc.read_h5ad(datasets[ds_key], backed='r')
var_df = ds_adata.var
var_df = var_df[var_df.ncells >0]
var_df = var_df[var_df.ncounts >0]
var_df.head()

,chr,start,end,class,strand,length,in_matrix,mean,std,cv,fano,ensembl_id,ncounts,ncells
gene_name,,,,,,,,,,,,,,
LINC01409,chr1,778747,810065,gene_version10,+,31318,True,0.116626,0.349971,3.000803,1.050194,ENSG00000237491,232036.0,214242
LINC01128,chr1,825138,868202,gene_version9,+,43064,True,0.182850,0.437274,2.391434,1.045713,ENSG00000228794,363795.0,325879
NOC2L,chr1,944203,959309,gene_version11,-,15106,True,1.415674,1.397208,0.986957,1.378984,ENSG00000188976,2816593.0,1391744
KLHL17,chr1,960584,965719,gene_version14,+,5135,True,0.105599,0.330678,3.131439,1.035497,ENSG00000187961,210098.0,196093
HES4,chr1,998962,1000172,gene_version10,-,1210,True,0.242700,0.550596,2.268630,1.249098,ENSG00000188290,482870.0,391564

In [44]:
new_genes = var_df.reset_index().set_index('ensembl_id')['gene_name'].to_dict()
len(new_genes.keys())

8248

In [45]:
# check conflicts, these are fine to overwrite
conflicts = {k: (all_genes[k], v) for k, v in new_genes.items() if k in all_genes and all_genes[k] != v}
conflicts

{'ENSG00000285053': ('TBCE', 'TBCE_ENSG00000285053'),
 'ENSG00000284770': ('TBCE', 'TBCE_ENSG00000284770'),
 'ENSG00000284024': ('HSPA14', 'HSPA14_ENSG00000284024'),
 'ENSG00000187522': ('HSPA14', 'HSPA14_ENSG00000187522')}

In [46]:
all_genes = {**new_genes, **all_genes}
len(all_genes)

10117

#### adamson

Review as this will be the smallest

In [47]:
ds_key = 'adamson'
ds_adata = sc.read_h5ad(datasets[ds_key], backed='r')
var_df = ds_adata.var
var_df = var_df[var_df.ncells >0]
var_df = var_df[var_df.ncounts >0]
var_df.head()

                    ensembl_id  ncounts  ncells
gene_symbol
MIR1302-10     ENSG00000243485     11.0      11
RP11-34P13.8   ENSG00000239945     43.0      43
AL627309.1     ENSG00000237683    337.0     333
AP006222.2     ENSG00000228463     48.0      48
RP4-669L17.10  ENSG00000237094      2.0       2

In [48]:
new_genes = var_df.reset_index().set_index('ensembl_id')['gene_symbol'].to_dict()
len(new_genes.keys())

23376

In [49]:
# check conflicts, these are fine to overwrite
conflicts = {k: (all_genes[k], v) for k, v in new_genes.items() if k in all_genes and all_genes[k] != v}
conflicts

{'ENSG00000237491': ('LINC01409', 'RP11-206L10.9'),
 'ENSG00000127054': ('INTS11', 'CPSF3L'),
 'ENSG00000224051': ('CPTP', 'GLTPD1'),
 'ENSG00000224870': ('MRPL20-AS1', 'RP4-758J18.2'),
 'ENSG00000228594': ('FNDC10', 'C1orf233'),
 'ENSG00000162585': ('FAAP20', 'C1orf86'),
 'ENSG00000157870': ('PRXL2B', 'FAM213B'),
 'ENSG00000231789': ('PIK3CD-AS2', 'RP11-558F24.4'),
 'ENSG00000175279': ('CENPS', 'APITD1'),
 'ENSG00000179743': ('AL450998.2', 'RP11-169K16.9'),
 'ENSG00000040487': ('SLC66A1', 'PQLC2'),
 'ENSG00000173436': ('MICOS10', 'MINOS1'),
 'ENSG00000261326': ('LINC01355', 'RP5-1057J7.6'),
 'ENSG00000011007': ('ELOA', 'TCEB3'),
 'ENSG00000236810': ('ELOA-AS1', 'RP5-886K2.3'),
 'ENSG00000117616': ('RSRP1', 'C1orf63'),
 'ENSG00000204178': ('MACO1', 'TMEM57'),
 'ENSG00000162430': ('SELENON', 'SEPN1'),
 'ENSG00000130770': ('ATP5IF1', 'ATPIF1'),
 'ENSG00000243749': ('TMEM35B', 'ZMYM6NB'),
 'ENSG00000183520': ('UTP11', 'UTP11L'),
 'ENSG00000259943': ('AL050341.2', 'RP1-39G22.7'),
 'ENSG00000117385': ('P3H1', 'LEPRE1'),
 'ENSG00000177868': ('SVBP', 'CCDC23'),
 'ENSG00000078618': ('NRDC', 'NRD1'),
 'ENSG00000134744': ('TUT4', 'ZCCHC11'),
 'ENSG00000162384': ('CZIB', 'C1orf123'),
 'ENSG00000162407': ('PLPP3', 'PPAP2B'),
 'ENSG00000132849': ('PATJ', 'INADL'),
 'ENSG00000230798': ('FOXD3-AS1', 'RP4-792G4.2'),
 'ENSG00000036549': ('AC118549.1', 'ZZZ3'),
 'ENSG00000180488': ('MIGA1', 'FAM73A'),
 'ENSG00000271576': ('AL359504.2', 'RP11-486G15.2'),
 'ENSG00000142871': ('CCN1', 'CYR61'),
 'ENSG00000183291': ('SELENOF', 'SEP15'),
 'ENSG00000137944': ('KYAT3', 'CCBL2'),
 'ENSG00000233593': ('LINC02609', 'RP4-665J23.1'),
 'ENSG00000154511': ('DIPK1A', 'FAM69A'),
 'ENSG00000156875': ('MFSD14A', 'HIAT1'),
 'ENSG00000233184': ('AC093157.1', 'RP11-421L21.3'),
 'ENSG00000273373': ('AL355488.1', 'RP5-1074L1.4'),
 'ENSG00000116459': ('ATP5PB', 'ATP5F1'),
 'ENSG00000232265': ('LINC02805', 'XXyac-YX155B6.5'),
 'ENSG00000232527': ('LINC02802', 'RP11-14N7.2'),
 'ENSG00000226067': ('LINC00623', 'LINC00869'),
 'ENSG00000143363': ('PRUNE1', 'PRUNE'),
 'ENSG00000132680': ('KHDC4', 'KIAA0907'),
 'ENSG00000198715': ('GLMP', 'C1orf85'),
 'ENSG00000163382': ('NAXE', 'APOA1BP'),
 'ENSG00000271736': ('LINC02772', 'RP11-85G21.3'),
 'ENSG00000183853': ('KIRREL1', 'KIRREL'),
 'ENSG00000010165': ('EEF1AKNMT', 'METTL13'),
 'ENSG00000143207': ('COP1', 'RFWD2'),
 'ENSG00000230124': ('ACBD6', 'RP5-1180C10.2'),
 'ENSG00000135842': ('NIBAN1', 'FAM129A'),
 'ENSG00000157181': ('ODR4', 'C1orf27'),
 'ENSG00000116747': ('RO60', 'TROVE2'),
 'ENSG00000117280': ('RAB29', 'RAB7L1'),
 'ENSG00000117597': ('UTP25', 'DIEXF'),
 'ENSG00000065600': ('PACC1', 'TMEM206'),
 'ENSG00000198468': ('FLVCR1-DT', 'FLVCR1-AS1'),
 'ENSG00000228106': ('AL392172.1', 'RP11-452F19.3'),
 'ENSG00000163050': ('COQ8A', 'ADCK3'),
 'ENSG00000177788': ('AL162595.1', 'RP5-1061H20.4'),
 'ENSG00000233461': ('AL445524.1', 'RP11-295G20.2'),
 'ENSG00000259865': ('AL390728.6', 'RP11-488L18.10'),
 'ENSG00000032389': ('EIPR1', 'TSSC1'),
 'ENSG00000242282': ('AC108488.1', 'AC108488.4'),
 'ENSG00000162976': ('SLC66A3', 'PQLC3'),
 'ENSG00000118961': ('LDAH', 'C2orf43'),
 'ENSG00000163026': ('WDCP', 'C2orf44'),
 'ENSG00000115128': ('SF3B6', 'SF3B14'),
 'ENSG00000138018': ('SELENOI', 'EPT1'),
 'ENSG00000158019': ('BABAM2', 'BRE'),
 'ENSG00000260025': ('CRIM1-DT', 'RP11-490M8.1'),
 'ENSG00000218739': ('CEBPZOS', 'CEBPZ-AS1'),
 'ENSG00000231312': ('MAP4K3-DT', 'AC007246.3'),
 'ENSG00000259439': ('LINC01833', 'RP11-89K21.1'),
 'ENSG00000115239': ('ASB3', 'GPR75-ASB3'),
 'ENSG00000163001': ('CFAP36', 'CCDC104'),
 'ENSG00000272711': ('AC019069.1', 'RP11-259N19.1'),
 'ENSG00000222041': ('CYTOR', 'LINC00152'),
 'ENSG00000230606': ('AC092683.1', 'AC159540.1'),
 'ENSG00000185414': ('MRPL30', 'MRPL30-1'),
 'ENSG00000272994': ('AC012360.3', 'RP11-332H14.2'),
 'ENSG00000175701': ('MTLN', 'LINC00116'),
 'ENSG00000172965': ('MIR4435-2HG', 'MIR4435-1HG'),
 'ENSG00000270190': ('AC068491.3', 'RP11-803D5.4'),
 'ENSG00000236255': ('AC009404.1', 'AC009404.2'),
 'ENSG00000234350': ('AC007405.1', 'AC007405.4'),
 'ENSG00000239467': ('AC007405.3', 'AC007405.6'),
 'ENSG00000091436': ('MAP3K20', 'MLTK'),
 'ENSG00000154518': ('ATP5MC3', 'ATP5G3'),
 'ENSG00000144320': ('LNPK', 'KIAA1715'),
 'ENSG00000223960': ('CHROMR', 'AC009948.5'),
 'ENSG00000138434': ('ITPRID2', 'SSFA2'),
 'ENSG00000162972': ('MAIP1', 'C2orf47'),
 'ENSG00000163535': ('SGO2', 'SGOL2'),
 'ENSG00000144580': ('CNOT9', 'RQCD1'),
 'ENSG00000144567': ('RETREG2', 'FAM134A'),
 'ENSG00000186235': ('LINC02610', 'AC016757.3'),
 'ENSG00000172428': ('COPS9', 'MYEOV2'),
 'ENSG00000260942': ('CAPN10-DT', 'CAPN10-AS1'),
 'ENSG00000122085': ('MTERF4', 'MTERFD2'),
 'ENSG00000168385': ('SEPTIN2', 'SEPT2'),
 'ENSG00000271870': ('AC024060.2', 'RP11-97C16.1'),
 'ENSG00000189229': ('AC069277.1', 'AC069277.2'),
 'ENSG00000206573': ('THUMPD3-AS1', 'SETD5-AS1'),
 'ENSG00000131381': ('RBSN', 'ZFYVE20'),
 'ENSG00000129810': ('SGO1', 'SGOL1'),
 'ENSG00000185614': ('INKA1', 'FAM212A'),
 'ENSG00000243477': ('NAA80', 'NAT6'),
 'ENSG00000145041': ('DCAF1', 'VPRBP'),
 'ENSG00000213533': ('STIMATE', 'TMEM110'),
 'ENSG00000113811': ('SELENOK', 'SELK'),
 'ENSG00000163946': ('TASOR', 'FAM208A'),
 'ENSG00000241316': ('SUCLG2-AS1', 'RP11-81N13.1'),
 'ENSG00000178700': ('DHFR2', 'DHFRL1'),
 'ENSG00000080200': ('CRYBG3', 'CRYBG3-1'),
 'ENSG00000170854': ('RIOX2', 'MINA'),
 'ENSG00000154174': ('TOMM70', 'TOMM70A'),
 'ENSG00000243701': ('DUBR', 'LINC00883'),
 'ENSG00000271856': ('LINC01215', 'RP11-861A13.4'),
 'ENSG00000163507': ('CIP2A', 'KIAA1524'),
 'ENSG00000177707': ('NECTIN3', 'PVRL3'),
 'ENSG00000163608': ('NEPRO', 'C3orf17'),
 'ENSG00000176542': ('USF3', 'KIAA2018'),
 'ENSG00000151576': ('QTRT2', 'QTRTD1'),
 'ENSG00000138463': ('SLC49A4', 'DIRC2'),
 'ENSG00000206527': ('HACD2', 'PTPLB'),
 'ENSG00000244300': ('GATA2-AS1', 'RP11-475N22.4'),
 'ENSG00000181744': ('DIPK2A', 'C3orf58'),
 'ENSG00000198843': ('SELENOT', 'SELT'),
 'ENSG00000174899': ('SLC66A1L', 'C3orf55'),
 'ENSG00000223812': ('AC073365.1', 'RP11-197K6.1'),
 'ENSG00000270170': ('NCBP2AS2', 'NCBP2-AS2'),
 'ENSG00000145016': ('RUBCN', 'KIAA0226'),
 'ENSG00000169020': ('ATP5ME', 'ATP5I'),
 'ENSG00000249592': ('AC139887.2', 'RP11-440L14.1'),
 'ENSG00000196810': ('CTBP1-DT', 'CTBP1-AS2'),
 'ENSG00000109685': ('NSD2', 'WHSC1'),
 'ENSG00000170846': ('AC093323.1', 'AC093323.3'),
 'ENSG00000152990': ('ADGRA3', 'GPR125'),
 'ENSG00000251129': ('LINC02506', 'RP11-734I18.1'),
 'ENSG00000261761': ('LINC02616', 'RP11-103J17.2'),
 'ENSG00000169429': ('CXCL8', 'IL8'),
 'ENSG00000118804': ('STBD1', 'FAM47E-STBD1-1'),
 'ENSG00000138758': ('SEPTIN11', 'SEPT11'),
 'ENSG00000163322': ('ABRAXAS1', 'FAM175A'),
 'ENSG00000138678': ('GPAT3', 'AGPAT9'),
 'ENSG00000246560': ('UBE2D3-AS1', 'RP11-10L12.4'),
 'ENSG00000005059': ('MCUB', 'CCDC109B'),
 'ENSG00000174749': ('FAM241A', 'C4orf32'),
 'ENSG00000138658': ('ZGRF1', 'C4orf21'),
 'ENSG00000164074': ('ABHD18', 'C4orf29'),
 'ENSG00000273247': ('AC097376.3', 'RP11-83A24.2'),
 'ENSG00000164169': ('PRMT9', 'PRMT10'),
 'ENSG00000059691': ('GATB', 'PET112'),
 'ENSG00000121210': ('TMEM131L', 'KIAA0922'),
 'ENSG00000056050': ('HPF1', 'C4orf27'),
 'ENSG00000164323': ('CFAP97', 'KIAA1430'),
 'ENSG00000221990': ('EXOC3-AS1', 'C5orf55'),
 'ENSG00000164151': ('ICE1', 'KIAA0947'),
 'ENSG00000112941': ('TENT4A', 'PAPD7'),
 'ENSG00000150756': ('ATPSCKMT', 'FAM173B'),
 'ENSG00000154124': ('OTULIN', 'FAM105B'),
 'ENSG00000154153': ('RETREG1', 'FAM134B'),
 'ENSG00000272086': ('AC025181.2', 'CTD-2186M15.3'),
 'ENSG00000197603': ('CPLANE1', 'C5orf42'),
 'ENSG00000250722': ('SELENOP', 'SEPP1'),
 'ENSG00000215068': ('AC025171.2', 'AC025171.1'),
 'ENSG00000151881': ('TMEM267', 'C5orf28'),
 'ENSG00000039123': ('MTREX', 'SKIV2L2'),
 'ENSG00000067113': ('PLPP1', 'PPAP2A'),
 'ENSG00000112851': ('ERBIN', 'ERBB2IP'),
 'ENSG00000085231': ('AK6', 'TAF9'),
 'ENSG00000113163': ('CERT1', 'COL4A3BP'),
 'ENSG00000245556': ('SCAMP1-AS1', 'CTD-2037K23.2'),
 'ENSG00000164329': ('TENT2', 'PAPD4'),
 'ENSG00000249042': ('AC008771.1', 'CTD-2015H6.3'),
 'ENSG00000133302': ('SLF1', 'ANKRD32'),
 'ENSG00000155324': ('GRAMD2B', 'GRAMD3'),
 'ENSG00000245937': ('LINC01184', 'CTC-228N24.3'),
 'ENSG00000164402': ('SEPTIN8', 'SEPT8'),
 'ENSG00000250159': ('AC106791.1', 'RP11-381K20.2'),
 'ENSG00000081791': ('DELE1', 'KIAA0141'),
 'ENSG00000204677': ('FAM153CP', 'FAM153C'),
 'ENSG00000161010': ('MRNIP', 'C5orf45'),
 'ENSG00000204628': ('RACK1', 'GNB2L1'),
 'ENSG00000233937': ('AC008443.1', 'CTC-338M12.4'),
 'ENSG00000079691': ('CARMIL1', 'LRRC16A'),
 'ENSG00000272501': ('AL662844.4', 'XXbac-BPG299F13.17'),
 'ENSG00000204420': ('MPIG6B', 'C6orf25'),
 'ENSG00000204387': ('SNHG32', 'C6orf48'),
 'ENSG00000204267': ('TAP2', 'TAP2-1'),
 'ENSG00000186577': ('SMIM29', 'C6orf1'),
 'ENSG00000196821': ('ILRUN', 'C6orf106'),
 'ENSG00000146085': ('MMUT', 'MUT'),
 'ENSG00000272316': ('AL021368.2', 'XXbac-BPGBPG55C20.2'),
 'ENSG00000227706': ('AL713998.1', 'RP11-301G19.1'),
 'ENSG00000229852': ('AC019205.1', 'RP11-398K22.12'),
 'ENSG00000112773': ('TENT5A', 'FAM46A'),
 'ENSG00000083097': ('DOP1A', 'DOPEY1'),
 'ENSG00000135315': ('CEP162', 'KIAA1009'),
 'ENSG00000112297': ('CRYBG1', 'AIM1'),
 'ENSG00000130349': ('MTRES1', 'C6orf203'),
 'ENSG00000135537': ('AFG1L', 'LACE1'),
 'ENSG00000173214': ('MFSD4B', 'KIAA1919'),
 'ENSG00000153975': ('ZUP1', 'ZUFSP'),
 'ENSG00000234147': ('AL035446.1', 'RP3-460G2.2'),
 'ENSG00000112414': ('ADGRG6', 'GPR126'),
 'ENSG00000146476': ('ARMT1', 'C6orf211'),
 'ENSG00000224893': ('LINC02840', 'RP1-200K18.1'),
 'ENSG00000130396': ('AFDN', 'MLLT4'),
 'ENSG00000164818': ('DNAAF5', 'HEATR2'),
 'ENSG00000229043': ('AC091729.3', 'AC091729.9'),
 'ENSG00000122687': ('MRM2', 'FTSJ2'),
 'ENSG00000219545': ('UMAD1', 'RPA3-AS1'),
 'ENSG00000136243': ('NUP42', 'NUPL2'),
 'ENSG00000105928': ('GSDME', 'DFNA5'),
 'ENSG00000271122': ('AC018647.2', 'RP11-379H18.1'),
 'ENSG00000122545': ('SEPTIN7', 'SEPT7'),
 'ENSG00000241127': ('YAE1', 'YAE1D1'),
 'ENSG00000106588': ('PSMA2', 'PSMA2-1'),
 'ENSG00000228434': ('AC004951.1', 'AC004951.6'),
 'ENSG00000205628': ('LINC01446', 'GS1-179L18.1'),
 'ENSG00000146729': ('NIPSNAP2', 'GBAS'),
 'ENSG00000239789': ('MRPS17', 'MRPS17-1'),
 'ENSG00000237310': ('AC008267.5', 'GS1-124K5.4'),
 'ENSG00000272831': ('AC027644.3', 'RP11-792A8.4'),
 'ENSG00000071462': ('BUD23', 'WBSCR22'),
 'ENSG00000214293': ('APTR', 'RSBN1L-AS1'),
 'ENSG00000127989': ('MTERF1', 'MTERF'),
 'ENSG00000004766': ('VPS50', 'CCDC132'),
 'ENSG00000127922': ('SEM1', 'SHFM1'),
 'ENSG00000196636': ('SDHAF3', 'ACN9'),
 'ENSG00000241468': ('ATP5MF', 'ATP5J2'),
 'ENSG00000232445': ('AC006329.1', 'RP11-132A1.4'),
 'ENSG00000128581': ('IFT22', 'RABL5'),
 'ENSG00000267368': ('UPK3BL1', 'UPK3BL'),
 'ENSG00000241764': ('AC002467.1', 'AC002467.7'),
 'ENSG00000234520': ('AC018464.1', 'AC018464.3'),
 'ENSG00000214194': ('SMIM30', 'LINC00998'),
 'ENSG00000128534': ('LSM8', 'NAA38'),
 'ENSG00000225546': ('LINC02476', 'RP11-328J2.1'),
 'ENSG00000272686': ('AC006333.2', 'RP11-390E23.6'),
 'ENSG00000226380': ('AC016831.1', 'MIR29A'),
 'ENSG00000271204': ('AC016831.5', 'RP11-138A9.1'),
 'ENSG00000122783': ('CYREN', 'C7orf49'),
 'ENSG00000243317': ('STMP1', 'C7orf73'),
 'ENSG00000164898': ('FMC1', 'C7orf55'),
 'ENSG00000146963': ('LUC7L2', 'C7orf55-LUC7L2'),
 'ENSG00000257093': ('DENND11', 'KIAA1147'),
 'ENSG00000232533': ('AC093673.1', 'AC093673.5'),
 'ENSG00000198420': ('TCAF1', 'FAM115A'),
 'ENSG00000216895': ('AC009403.1', 'AC009403.2'),
 'ENSG00000130021': ('PUDP', 'HDHD1'),
 'ENSG00000270069': ('MIR222HG', 'RP6-99M1.2'),
 'ENSG00000185222': ('TCEAL9', 'WBP5'),
 'ENSG00000166681': ('BEX3', 'NGFRAP1'),
 'ENSG00000241743': ('XACT', 'RP5-964N17.1'),
 'ENSG00000125354': ('SEPTIN6', 'SEPT6'),
 'ENSG00000134602': ('STK26', 'MST4'),
 'ENSG00000134590': ('RTL8C', 'FAM127A'),
 'ENSG00000203950': ('RTL8A', 'FAM127B'),
 'ENSG00000232611': ('AL683813.1', 'RP11-1114A5.4'),
 'ENSG00000253982': ('AC100810.1', 'CTD-2336O2.1'),
 'ENSG00000254319': ('AC246817.2', 'RP11-134O21.1'),
 'ENSG00000253853': ('AC246817.1', 'GS1-57L11.1'),
 'ENSG00000246089': ('AC016065.1', 'RP11-115C21.2'),
 'ENSG00000133872': ('SARAF', 'TMEM66'),
 'ENSG00000253642': ('AF279873.3', 'RP11-317N12.1'),
 'ENSG00000147471': ('PLPBP', 'PROSC'),
 'ENSG00000147535': ('PLPP5', 'PPAPDC1B'),
 'ENSG00000147548': ('NSD3', 'WHSC1L1'),
 'ENSG00000158669': ('GPAT4', 'AGPAT6'),
 'ENSG00000154582': ('ELOC', 'TCEB1'),
 'ENSG00000176731': ('RBIS', 'C8orf59'),
 'ENSG00000251136': ('AF117829.1', 'RP11-37B2.1'),
 'ENSG00000155099': ('PIP4P2', 'TMEM55A'),
 'ENSG00000253738': ('OTUD6B-AS1', 'GS1-251I9.4'),
 'ENSG00000188343': ('FAM92A', 'FAM92A1'),
 'ENSG00000164944': ('VIRMA', 'KIAA1429'),
 'ENSG00000156469': ('MTERF3', 'MTERFD1'),
 'ENSG00000132541': ('RIDA', 'HRSP12'),
 'ENSG00000254615': ('AC027031.2', 'RP11-395G23.3'),
 'ENSG00000164961': ('WASHC5', 'KIAA0196'),
 'ENSG00000254101': ('LINC02055', 'RP11-30J20.1'),
 'ENSG00000253716': ('MINCR', 'RP13-582O9.5'),
 'ENSG00000147813': ('NAPRT', 'NAPRT1'),
 'ENSG00000104524': ('PYCR3', 'PYCRL'),
 'ENSG00000235173': ('HGH1', 'FAM203A'),
 'ENSG00000080608': ('PUM3', 'KIAA0020'),
 'ENSG00000107036': ('RIC1', 'KIAA1432'),
 'ENSG00000137038': ('DMAC1', 'TMEM261'),
 'ENSG00000235453': ('SMIM27', 'TOPORS-AS1'),
 'ENSG00000231527': ('FAM27C', 'RP11-374M1.2'),
 'ENSG00000135048': ('CEMIP2', 'TMEM2'),
 'ENSG00000156017': ('CARNMT1', 'C9orf41'),
 'ENSG00000083223': ('TUT7', 'ZCCHC6'),
 'ENSG00000165233': ('CARD19', 'C9orf89'),
 'ENSG00000269929': ('AL158152.1', 'RP11-2B6.2'),
 'ENSG00000148110': ('MFSD14B', 'HIATL1'),
 'ENSG00000148120': ('AOPEP', 'C9orf3'),
 'ENSG00000158122': ('PRXL2C', 'AAED1'),
 'ENSG00000196312': ('MFSD14C', 'HIATL2'),
 'ENSG00000136932': ('TRMO', 'C9orf156'),
 'ENSG00000070061': ('ELP1', 'IKBKAP'),
 'ENSG00000119328': ('ABITRAM', 'FAM206A'),
 'ENSG00000136813': ('ECPAS', 'KIAA0368'),
 'ENSG00000157693': ('TMEM268', 'C9orf91'),
 'ENSG00000136830': ('NIBAN2', 'FAM129B'),
 'ENSG00000223478': ('AL441992.1', 'RP11-545E17.3'),
 'ENSG00000198917': ('SPOUT1', 'C9orf114'),
 'ENSG00000148343': ('MIGA2', 'FAM73B'),
 'ENSG00000119383': ('PTPA', 'PPP2R4'),
 'ENSG00000246851': ('AL157938.3', 'RP11-544A12.8'),
 'ENSG00000165698': ('SPACA9', 'C9orf9'),
 'ENSG00000235106': ('BRD3OS', 'LINC00094'),
 'ENSG00000238227': ('TMEM250', 'C9orf69'),
 'ENSG00000165689': ('ENTR1', 'SDCCAG3'),
 'ENSG00000165716': ('DIPK1B', 'FAM69B'),
 'ENSG00000148362': ('PAXX', 'C9orf142'),
 'ENSG00000268996': ('MAN1B1-DT', 'AL807752.1'),
 'ENSG00000203993': ('ARRDC1-AS1', 'C9orf37'),
 'ENSG00000242147': ('LINC02657', 'RP13-463N16.6'),
 'ENSG00000108021': ('TASOR2', 'FAM208B'),
 'ENSG00000134452': ('FBH1', 'FBXO18'),
 'ENSG00000165629': ('ATP5F1C', 'ATP5C1'),
 'ENSG00000148481': ('MINDY3', 'FAM188A'),
 'ENSG00000165996': ('HACD1', 'PTPLA'),
 'ENSG00000172661': ('WASHC2C', 'FAM21C'),
 'ENSG00000204161': ('TMEM273', 'C10orf128'),
 'ENSG00000099290': ('WASHC2A', 'FAM21A'),
 'ENSG00000228065': ('LINC01515', 'RP11-222A11.1'),
 'ENSG00000198954': ('KIF1BP', 'KIAA1279'),
 'ENSG00000171224': ('FAM241B', 'C10orf35'),
 'ENSG00000107738': ('VSIR', 'C10orf54'),
 'ENSG00000148655': ('LRMDA', 'C10orf11'),
 'ENSG00000225484': ('NUTM2B-AS1', 'RP11-773D16.1'),
 'ENSG00000122378': ('PRXL2A', 'FAM213A'),
 'ENSG00000062650': ('WAPL', 'WAPAL'),
 'ENSG00000122376': ('SHLD2', 'FAM35A'),
 'ENSG00000166136': ('NDUFB8', 'NDUFB8-1'),
 'ENSG00000119906': ('SLF2', 'FAM178A'),
 'ENSG00000107815': ('TWNK', 'C10orf2'),
 'ENSG00000198408': ('OGA', 'MGEA5'),
 'ENSG00000120029': ('ARMH3', 'C10orf76'),
 'ENSG00000166275': ('BORCS7', 'C10orf32'),
 'ENSG00000173915': ('ATP5MD', 'USMG5'),
 'ENSG00000107960': ('STN1', 'OBFC1'),
 'ENSG00000165813': ('CCDC186', 'C10orf118'),
 'ENSG00000187164': ('SHTN1', 'KIAA1598'),
 'ENSG00000119979': ('DENND10', 'FAM45A'),
 'ENSG00000203805': ('PLPP4', 'PPAPDC1A'),
 'ENSG00000203791': ('EEF1AKMT2', 'METTL10'),
 'ENSG00000165660': ('ABRAXAS2', 'FAM175B'),
 'ENSG00000177225': ('GATD1', 'PDDC1'),
 'ENSG00000255284': ('AP006621.3', 'AP006621.5'),
 'ENSG00000260196': ('AC124798.1', 'RP1-239B22.5'),
 'ENSG00000254560': ('BBOX1-AS1', 'RP11-1L12.3'),
 'ENSG00000211450': ('SELENOH', 'C11orf31'),
 'ENSG00000149476': ('TKFC', 'DAK'),
 'ENSG00000214756': ('CSKMT', 'METTL12'),
 'ENSG00000204922': ('UQCC3', 'C11orf83'),
 'ENSG00000133321': ('PLAAT4', 'RARRES3'),
 'ENSG00000176485': ('PLAAT3', 'PLA2G16'),
 'ENSG00000168005': ('SPINDOC', 'C11orf84'),
 'ENSG00000256940': ('PPP1R14B-AS1', 'RP11-783K16.5'),
 'ENSG00000173465': ('ZNRD2', 'SSSCA1'),
 'ENSG00000197136': ('PCNX3', 'PCNXL3'),
 'ENSG00000174684': ('B4GAT1', 'B3GNT1'),
 'ENSG00000173020': ('GRK2', 'ADRBK1'),
 'ENSG00000110066': ('KMT5B', 'SUV420H1'),
 'ENSG00000149716': ('LTO1', 'ORAOV1'),
 'ENSG00000254682': ('AP002387.2', 'RP11-660L16.2'),
 'ENSG00000137492': ('THAP12', 'PRKRIR'),
 'ENSG00000179240': ('GVQW3', 'RP11-111M22.2'),
 'ENSG00000255135': ('AP002360.1', 'RP11-111M22.3'),
 'ENSG00000158636': ('EMSY', 'C11orf30'),
 'ENSG00000165490': ('DDIAS', 'C11orf82'),
 'ENSG00000246067': ('RAB30-DT', 'RAB30-AS1'),
 'ENSG00000149196': ('HIKESHI', 'C11orf73'),
 'ENSG00000166004': ('CEP295', 'KIAA1731'),
 'ENSG00000020922': ('MRE11', 'MRE11A'),
 'ENSG00000110318': ('CEP126', 'KIAA1377'),
 'ENSG00000137691': ('CFAP300', 'C11orf70'),
 'ENSG00000178202': ('POGLUT3', 'KDELC2'),
 'ENSG00000150776': ('NKAPD1', 'C11orf57'),
 'ENSG00000109917': ('ZPR1', 'ZNF259'),
 'ENSG00000167283': ('ATP5MG', 'ATP5L'),
 'ENSG00000181264': ('TLCD5', 'TMEM136'),
 'ENSG00000182934': ('SRPRA', 'SRPR'),
 'ENSG00000078237': ('TIGAR', 'C12orf5'),
 'ENSG00000245648': ('AC022075.1', 'RP11-277P12.20'),
 'ENSG00000165714': ('BORCS5', 'LOH12CR1'),
 'ENSG00000247498': ('GPRC5D-AS1', 'RP11-392P7.6'),
 'ENSG00000205707': ('ETFRF1', 'LYRM5'),
 'ENSG00000064102': ('INTS13', 'ASUN'),
 'ENSG00000139146': ('SINHCAF', 'FAM60A'),
 'ENSG00000174718': ('RESF1', 'KIAA1551'),
 'ENSG00000273015': ('AC008124.1', 'LINC00938'),
 'ENSG00000123395': ('ATG101', 'C12orf44'),
 'ENSG00000111077': ('TNS2', 'TENC1'),
 'ENSG00000257605': ('AC073611.1', 'RP11-680A11.5'),
 'ENSG00000135390': ('ATP5MC2', 'ATP5G2'),
 'ENSG00000170473': ('PYM1', 'WIBG'),
 'ENSG00000110955': ('ATP5F1B', 'ATP5B'),
 'ENSG00000166881': ('NEMP1', 'TMEM194A'),
 'ENSG00000257698': ('GIHCG', 'RP11-620J15.3'),
 'ENSG00000166896': ('ATP23', 'XRCC6BP1'),
 'ENSG00000198673': ('TAFA2', 'FAM19A2'),
 'ENSG00000257354': ('AC048341.1', 'RP11-631N16.2'),
 'ENSG00000118600': ('RXYLT1', 'TMEM5'),
 'ENSG00000256268': ('LINC02454', 'RP11-221N13.3'),
 'ENSG00000155957': ('TMBIM4', 'TMBIM4-1'),
 'ENSG00000257815': ('AC025159.1', 'RP11-611E13.2'),
 'ENSG00000251138': ('AC090015.1', 'RP11-81H3.2'),
 'ENSG00000173588': ('CEP83', 'CCDC41'),
 'ENSG00000120860': ('WASHC3', 'CCDC53'),
 'ENSG00000257732': ('AC089983.1', 'RP11-818F20.5'),
 'ENSG00000136051': ('WASHC4', 'KIAA1033'),
 'ENSG00000151135': ('TMEM263', 'C12orf23'),
 'ENSG00000120832': ('MTERF2', 'MTERFD3'),
 'ENSG00000089154': ('GCN1', 'GCN1L1'),
 'ENSG00000248008': ('NRAV', 'DYNLL1-AS1'),
 'ENSG00000212694': ('LINC01089', 'AC084018.1'),
 'ENSG00000256092': ('SBNO1-AS1', 'hsa-mir-8072'),
 'ENSG00000183955': ('KMT5A', 'SETD8'),
 'ENSG00000150456': ('EEF1AKMT1', 'N6AMT2'),
 'ENSG00000173141': ('MRPL57', 'MRP63'),
 'ENSG00000139496': ('NUP58', 'NUPL1'),
 'ENSG00000187676': ('B3GLCT', 'B3GALTL'),
 'ENSG00000133104': ('SPART', 'SPG20'),
 'ENSG00000183722': ('LHFPL6', 'LHFP'),
 'ENSG00000152193': ('OBI1', 'RNF219'),
 'ENSG00000247400': ('DNAJC3-DT', 'DNAJC3-AS1'),
 'ENSG00000134901': ('POGLUT2', 'KDELC1'),
 'ENSG00000213995': ('NAXD', 'CARKD'),
 'ENSG00000272695': ('GAS6-DT', 'GAS6-AS2'),
 'ENSG00000165782': ('PIP4P1', 'TMEM55B'),
 'ENSG00000258081': ('AL110292.1', 'RP11-384J4.2'),
 'ENSG00000258038': ('LINC02327', 'CTD-2384A14.1'),
 'ENSG00000258738': ('AL121603.2', 'RP11-73E17.2'),
 'ENSG00000100890': ('PRORP', 'KIAA0391'),
 'ENSG00000150527': ('MIA2', 'CTAGE5'),
 'ENSG00000251363': ('LINC02315', 'RP11-129M6.1'),
 'ENSG00000198718': ('TOGARAM1', 'FAM179B'),

In [50]:
all_genes = {**new_genes, **all_genes}
len(all_genes)

23750

#### norman

In [51]:
ds_key = 'norman'
ds_adata = sc.read_h5ad(datasets[ds_key], backed='r')
var_df = ds_adata.var
var_df = var_df[var_df.ncells >0]
var_df = var_df[var_df.ncounts >0]
var_df.head()

                  ensemble_id  ncounts  ncells
RP11-34P13.3  ENSG00000243485     29.0      29
RP11-34P13.7  ENSG00000238009    266.0     265
RP11-34P13.8  ENSG00000239945     10.0      10
RP11-34P13.9  ENSG00000241599      1.0       1
FO538757.3    ENSG00000279928     12.0      12

In [53]:
new_genes = var_df.reset_index().set_index('ensemble_id')['index'].to_dict()
len(new_genes.keys())

25038

In [55]:
# check conflicts, these are fine to overwrite
conflicts = {k: (all_genes[k], v) for k, v in new_genes.items() if k in all_genes and all_genes[k] != v}
conflicts

{'ENSG00000243485': ('MIR1302-10', 'RP11-34P13.3'),
 'ENSG00000237491': ('LINC01409', 'RP11-206L10.9'),
 'ENSG00000187642': ('C1orf170', 'PERM1'),
 'ENSG00000223823': ('RP11-465B22.5', 'LINC01342'),
 'ENSG00000127054': ('INTS11', 'CPSF3L'),
 'ENSG00000215014': ('AL645728.1', 'RP5-832C2.5'),
 'ENSG00000228594': ('FNDC10', 'C1orf233'),
 'ENSG00000142609': ('C1orf222', 'CFAP74'),
 'ENSG00000157870': ('PRXL2B', 'FAM213B'),
 'ENSG00000233304': ('RP13-614K11.1', 'LINC01346'),
 'ENSG00000179840': ('C1orf200', 'PIK3CD-AS1'),
 'ENSG00000175279': ('CENPS', 'APITD1'),
 'ENSG00000179743': ('AL450998.2', 'FLJ37453'),
 'ENSG00000233421': ('U1', 'RP5-875O13.1'),
 'ENSG00000228549': ('U1-1', 'RP11-108M9.3'),
 'ENSG00000040487': ('SLC66A1', 'PQLC2'),
 'ENSG00000173436': ('MICOS10', 'MINOS1'),
 'ENSG00000249087': ('C1orf213', 'ZNF436-AS1'),
 'ENSG00000011007': ('ELOA', 'TCEB3'),
 'ENSG00000236810': ('ELOA-AS1', 'TCEB3-AS1'),
 'ENSG00000204178': ('MACO1', 'TMEM57'),
 'ENSG00000162430': ('SELENON', 'SEPN1'),
 'ENSG00000175707': ('C1orf172', 'KDF1'),
 'ENSG00000130770': ('ATP5IF1', 'ATPIF1'),
 'ENSG00000223382': ('RP1-65J11.1', 'RP5-1125N11.2'),
 'ENSG00000223907': ('RP11-439L8.4', 'LINC01226'),
 'ENSG00000121753': ('BAI2', 'ADGRB2'),
 'ENSG00000142920': ('ADC', 'AZIN2'),
 'ENSG00000243749': ('TMEM35B', 'ZMYM6NB'),
 'ENSG00000183520': ('UTP11', 'UTP11L'),
 'ENSG00000259943': ('AL050341.2', 'RP1-39G22.7'),
 'ENSG00000243710': ('WDR65', 'CFAP57'),
 'ENSG00000225762': ('RP11-511I2.2', 'LINC01389'),
 'ENSG00000203356': ('RP11-296A18.3', 'LINC01562'),
 'ENSG00000261664': ('RP11-275F13.1', 'TTC39A-AS1'),
 'ENSG00000134744': ('TUT4', 'ZCCHC11'),
 'ENSG00000162384': ('CZIB', 'C1orf123'),
 'ENSG00000237352': ('RP11-145M4.3', 'LINC01358'),
 'ENSG00000237928': ('RP4-668G5.1', 'NFIA-AS2'),
 'ENSG00000132849': ('PATJ', 'INADL'),
 'ENSG00000223949': ('RP11-24J23.2', 'ROR1-AS1'),
 'ENSG00000234264': ('RP4-694A7.4', 'DEPDC1-AS1'),
 'ENSG00000233973': ('RP4-598G3.1', 'LINC01360'),
 'ENSG00000178965': ('C1orf173', 'ERICH3'),
 'ENSG00000036549': ('AC118549.1', 'ZZZ3'),
 'ENSG00000180488': ('MIGA1', 'FAM73A'),
 'ENSG00000236268': ('RP11-170N11.1', 'LINC01361'),
 'ENSG00000271576': ('AL359504.2', 'RP11-486G15.2'),
 'ENSG00000180869': ('C1orf180', 'LINC01555'),
 'ENSG00000282057': ('AC092807.3', 'RP4-621F18.2'),
 'ENSG00000142871': ('CCN1', 'CYR61'),
 'ENSG00000183291': ('SELENOF', 'SEP15'),
 'ENSG00000237505': ('RP11-76N22.2', 'PKN2-AS1'),
 'ENSG00000137944': ('KYAT3', 'CCBL2'),
 'ENSG00000231999': ('RP5-1007M22.2', 'FLJ27354'),
 'ENSG00000233593': ('LINC02609', 'RP4-665J23.1'),
 'ENSG00000154511': ('DIPK1A', 'FAM69A'),
 'ENSG00000224616': ('RP11-305E17.6', 'RTCA-AS1'),
 'ENSG00000233184': ('AC093157.1', 'RP11-421L21.3'),
 'ENSG00000231671': ('RP11-157N3.1', 'LINC01307'),
 'ENSG00000273373': ('AL355488.1', 'RP5-1074L1.4'),
 'ENSG00000116459': ('ATP5PB', 'ATP5F1'),
 'ENSG00000121933': ('ADORA3', 'TMIGD3'),
 'ENSG00000215866': ('RP11-426L16.8', 'LINC01356'),
 'ENSG00000235527': ('RP5-1073O3.7', 'HIPK1-AS1'),
 'ENSG00000230806': ('RP11-343N15.1', 'SRGAP2-AS1'),
 'ENSG00000227082': ('AL592494.5', 'CH17-437K3.1'),
 'ENSG00000232527': ('LINC02802', 'RP11-14N7.2'),
 'ENSG00000162825': ('NBPF8', 'NBPF20'),
 'ENSG00000213240': ('NOTCH2NL', 'RP11-458D21.5'),
 'ENSG00000264343': ('NOTCH2NLA', 'NOTCH2NL'),
 'ENSG00000232265': ('LINC02805', 'XXyac-YX155B6.5'),
 'ENSG00000274265': ('AC245297.3', 'CH17-189H20.1'),
 'ENSG00000159208': ('C1orf51', 'CIART'),
 'ENSG00000228126': ('LINC00568', 'FALEC'),
 'ENSG00000143363': ('PRUNE1', 'PRUNE'),
 'ENSG00000229021': ('NBPF18P', 'AL591893.1'),
 'ENSG00000132680': ('KHDC4', 'KIAA0907'),
 'ENSG00000163382': ('NAXE', 'APOA1BP'),
 'ENSG00000271736': ('LINC02772', 'RP11-85G21.3'),
 'ENSG00000183853': ('KIRREL1', 'KIRREL'),
 'ENSG00000213088': ('DARC', 'ACKR1'),
 'ENSG00000213085': ('CCDC19', 'CFAP45'),
 'ENSG00000258465': ('DCAF8-1', 'RP11-574F21.3'),
 'ENSG00000188931': ('C1orf192', 'CFAP126'),
 'ENSG00000185860': ('C1orf110', 'CCDC190'),
 'ENSG00000232995': ('RP11-267N12.3', 'RGS5-1'),
 'ENSG00000010165': ('EEF1AKNMT', 'METTL13'),
 'ENSG00000143207': ('COP1', 'RFWD2'),
 'ENSG00000232586': ('RP11-46A10.4', 'KIAA1614-AS1'),
 'ENSG00000228918': ('GS1-122H1.2', 'LINC01344'),
 'ENSG00000135842': ('NIBAN1', 'FAM129A'),
 'ENSG00000157181': ('ODR4', 'C1orf27'),
 'ENSG00000116747': ('RO60', 'TROVE2'),
 'ENSG00000223396': ('RPS10P7', 'RP11-134G8.5'),
 'ENSG00000231507': ('RP11-134P9.3', 'LINC01353'),
 'ENSG00000162894': ('FAIM3', 'FCMR'),
 'ENSG00000117597': ('UTP25', 'DIEXF'),
 'ENSG00000065600': ('PACC1', 'TMEM206'),
 'ENSG00000260805': ('RP11-61J19.4', 'RP11-61J19.5'),
 'ENSG00000185523': ('C1orf227', 'SPATA45'),
 'ENSG00000198468': ('FLVCR1-DT', 'FLVCR1-AS1'),
 'ENSG00000232480': ('RP11-224O19.2', 'TGFB2-AS1'),
 'ENSG00000228063': ('RP11-135J2.4', 'LYPLAL1-AS1'),
 'ENSG00000238078': ('RP11-295M18.2', 'LINC01352'),
 'ENSG00000257551': ('HLA-AS1', 'HLX-AS1'),
 'ENSG00000234754': ('RP11-421L10.1', 'C1orf140'),
 'ENSG00000225265': ('RP11-378J18.3', 'TAF1A-AS1'),
 'ENSG00000228106': ('AL392172.1', 'RP11-452F19.3'),
 'ENSG00000163050': ('COQ8A', 'ADCK3'),
 'ENSG00000177788': ('AL162595.1', 'RP5-1061H20.4'),
 'ENSG00000233461': ('AL445524.1', 'RP11-295G20.2'),
 'ENSG00000143674': ('MLK4', 'RP5-862P8.2'),
 'ENSG00000231768': ('RP5-855F14.1', 'LINC01354'),
 'ENSG00000086619': ('ERO1LB', 'ERO1B'),
 'ENSG00000231512': ('RP11-261C10.2', 'LINC01347'),
 'ENSG00000135747': ('ZNF670', 'ZNF670-ZNF695'),
 'ENSG00000259865': ('AL390728.6', 'RP11-488L18.10'),
 'ENSG00000234423': ('AC019118.2', 'LINC01250'),
 'ENSG00000032389': ('EIPR1', 'TSSC1'),
 'ENSG00000242282': ('AC108488.1', 'AC108488.4'),
 'ENSG00000231532': ('AC022311.1', 'LINC01249'),
 'ENSG00000225964': ('AC017076.5', 'NRIR'),
 'ENSG00000235092': ('AC011747.7', 'ID2-AS1'),
 'ENSG00000162976': ('SLC66A3', 'PQLC3'),
 'ENSG00000224184': ('AC096559.1', 'MIR3681HG'),
 'ENSG00000223850': ('MYCNUN', 'MYCNUT'),
 'ENSG00000236204': ('AC092594.1', 'LINC01376'),
 'ENSG00000163026': ('WDCP', 'C2orf44'),
 'ENSG00000157833': ('GAREML', 'GAREM2'),
 'ENSG00000173567': ('GPR113', 'ADGRF3'),
 'ENSG00000138018': ('SELENOI', 'EPT1'),
 'ENSG00000234945': ('AC109828.1', 'GTF3C2-AS1'),
 'ENSG00000205334': ('AC074091.13', 'LINC01460'),
 'ENSG00000158019': ('BABAM2', 'BRE'),
 'ENSG00000203386': ('AC009499.1', 'LINC01317'),
 'ENSG00000260025': ('CRIM1-DT', 'RP11-490M8.1'),
 'ENSG00000231312': ('MAP4K3-DT', 'AC007246.3'),
 'ENSG00000259439': ('LINC01833', 'RP11-89K21.1'),
 'ENSG00000235760': ('AC138655.4', 'HCG2040054'),
 'ENSG00000270898': ('ASB3', 'GPR75-ASB3'),
 'ENSG00000228414': ('AC010733.4', 'LINC01185'),
 'ENSG00000239322': ('AC007040.7', 'ATP6V1B1-AS1'),
 'ENSG00000217702': ('MGC10955', 'RP11-287D1.4'),
 'ENSG00000272711': ('AC019069.1', 'RP11-259N19.1'),
 'ENSG00000204792': ('AC104135.3', 'LINC01291'),
 'ENSG00000232504': ('AC105053.4', 'ST3GAL5-AS1'),
 'ENSG00000222041': ('CYTOR', 'LINC00152'),
 'ENSG00000230606': ('AC092683.1', 'AC159540.1'),
 'ENSG00000273045': ('C2ORF15', 'C2orf15'),
 'ENSG00000241962': ('C2orf15', 'RP11-111H13.1'),
 'ENSG00000273155': ('MRPL30', 'RP11-38C17.1'),
 'ENSG00000231851': ('AC104655.2', 'UTAT33'),
 'ENSG00000272994': ('AC012360.3', 'RP11-332H14.2'),
 'ENSG00000214184': ('AC012487.2', 'GCC2-AS1'),
 'ENSG00000186522': ('SEPTIN10', 'SEPT10'),
 'ENSG00000175701': ('MTLN', 'LINC00116'),
 'ENSG00000270190': ('AC068491.3', 'RP11-803D5.4'),
 'ENSG00000231943': ('RP11-395L14.4', 'PGM5P4-AS1'),
 'ENSG00000234199': ('AC010982.1', 'LINC01191'),
 'ENSG00000236255': ('AC009404.1', 'AC009404.2'),
 'ENSG00000183292': ('AC140481.2', 'TISP43'),
 'ENSG00000231890': ('AC093391.2', 'DARS-AS1'),
 'ENSG00000232606': ('AC010090.1', 'LINC01412'),
 'ENSG00000234350': ('AC007405.1', 'AC007405.4'),
 'ENSG00000239467': ('AC007405.3', 'AC007405.6'),
 'ENSG00000236651': ('AC104801.1', 'DLX2-AS1'),
 'ENSG00000091436': ('MAP3K20', 'AC013461.1'),
 'ENSG00000231453': ('AC018470.4', 'LINC01305'),
 'ENSG00000154518': ('ATP5MC3', 'ATP5G3'),
 'ENSG00000144320': ('LNPK', 'KIAA1715'),
 'ENSG00000224189': ('HOXD-AS1', 'HAGLR'),
 'ENSG00000226363': ('AC009336.24', 'HAGLROS'),
 'ENSG00000223960': ('CHROMR', 'AC009948.5'),
 'ENSG00000138434': ('ITPRID2', 'SSFA2'),
 'ENSG00000231646': ('AC008174.3', 'FSIP2-AS1'),
 'ENSG00000237877': ('AC097500.2', 'LINC01473'),
 'ENSG00000189362': ('TMEM194B', 'NEMP2'),
 'ENSG00000162972': ('MAIP1', 'C2orf47'),
 'ENSG00000163535': ('SGO2', 'SGOL2'),
 'ENSG00000182329': ('AC079354.1', 'KIAA2012'),
 'ENSG00000234281': ('AC007970.1', 'LANCL1-AS1'),
 'ENSG00000260804': ('RP11-566E18.3', 'PKI55'),
 'ENSG00000237281': ('AC021016.8', 'CATIP-AS2'),
 'ENSG00000158428': ('C2orf62', 'CATIP'),
 'ENSG00000144580': ('CNOT9', 'RQCD1'),
 'ENSG00000228135': ('AC073128.10', 'LINC01494'),
 'ENSG00000181378': ('CCDC108', 'CFAP65'),
 'ENSG00000144567': ('RETREG2', 'FAM134A'),
 'ENSG00000241635': ('UGT1A8', 'UGT1A1'),
 'ENSG00000232893': ('AC019068.2', 'IQCA1-AS1'),
 'ENSG00000172428': ('COPS9', 'MYEOV2'),
 'ENSG00000260942': ('CAPN10-DT', 'CAPN10-AS1'),
 'ENSG00000168385': ('SEPTIN2', 'SEPT2'),
 'ENSG00000188011': ('CXXC11', 'RTP5'),
 'ENSG00000271870': ('AC024060.2', 'RP11-97C16.1'),
 'ENSG00000268509': ('AC026202.1', 'RP11-572B2.1'),
 'ENSG00000189229': ('AC069277.1', 'AC069277.2'),
 'ENSG00000225526': ('C3orf83', 'MKRN2OS'),
 'ENSG00000251576': ('RP11-536I6.1', 'LINC01267'),
 'ENSG00000129810': ('SGO1', 'SGOL1'),
 'ENSG00000240747': ('KRBOX1-1', 'KRBOX1'),
 'ENSG00000268324': ('LUZPP1', 'LRRC2-AS1'),
 'ENSG00000164053': ('ATRIP', 'ATRIP-1'),
 'ENSG00000228350': ('RP11-148G20.1', 'CELSR3-AS1'),
 'ENSG00000185614': ('INKA1', 'FAM212A'),
 'ENSG00000235016': ('RP11-493K19.3', 'SEMA3F-AS1'),
 'ENSG00000243477': ('NAA80', 'NAT6'),
 'ENSG00000271858': ('XXcos-LUCA11.4', 'CYB561D2-1'),
 'ENSG00000145041': ('DCAF1', 'VPRBP'),
 'ENSG00000213533': ('STIMATE', 'TMEM110'),
 'ENSG00000113811': ('SELENOK', 'SELK'),
 'ENSG00000163946': ('TASOR', 'FAM208A'),
 'ENSG00000272146': ('RP11-755B10.4', 'ARF4-AS1'),
 'ENSG00000239801': ('RP11-755B10.2', 'DENND6A-AS1'),
 'ENSG00000240405': ('RP11-460N16.1', 'LINC01212'),
 'ENSG00000178700': ('DHFR2', 'DHFRL1'),
 'ENSG00000170854': ('RIOX2', 'MINA'),
 'ENSG00000154174': ('TOMM70', 'TOMM70A'),
 'ENSG00000163507': ('CIP2A', 'KIAA1524'),
 'ENSG00000228980': ('RP11-702L6.4', 'LINC01205'),
 'ENSG00000177707': ('NECTIN3', 'PVRL3'),
 'ENSG00000163608': ('NEPRO', 'C3orf17'),
 'ENSG00000206530': ('WDR52', 'CFAP44'),
 'ENSG00000163617': ('KIAA1407', 'CCDC191'),
 'ENSG00000151576': ('QTRT2', 'QTRTD1'),
 'ENSG00000138463': ('SLC49A4', 'DIRC2'),
 'ENSG00000198685': ('C3orf27', 'LINC01565'),
 'ENSG00000239213': ('RP11-85F14.5', 'NCK1-AS1'),
 'ENSG00000244578': ('RP11-548O1.3', 'LINC01391'),
 'ENSG00000206262': ('C3orf72', 'FOXL2NB'),
 'ENSG00000155893': ('ACPL2', 'PXYLP1'),
 'ENSG00000241570': ('RP11-372E1.6', 'PAQR9-AS1'),
 'ENSG00000181744': ('DIPK2A', 'C3orf58'),
 'ENSG00000244541': ('RP11-167H9.6', 'LINC01213'),
 'ENSG00000198843': ('SELENOT', 'SELT'),
 'ENSG00000240137': ('RP11-103G8.2', 'ERICH6-AS1'),
 'ENSG00000241369': ('CT64', 'LINC01192'),
 'ENSG00000244128': ('RP11-85M11.2', 'LINC01322'),
 'ENSG00000223715': ('RP11-71G7.1', 'LINC01208'),
 'ENSG00000228308': ('RP11-255G21.1', 'LINC01209'),
 'ENSG00000237978': ('RP11-385J1.2', 'KCNMB2-AS1'),
 'ENSG00000163915': ('C3orf65', 'IGF2BP2-AS1'),
 'ENSG00000225764': ('LEPREL1-AS1', 'P3H2-AS1'),
 'ENSG00000223812': ('AC073365.1', 'RP11-197K6.1'),
 'ENSG00000273331': ('TM4SF19', 'TM4SF19-TCTEX1D2'),
 'ENSG00000145107': ('TM4SF19-1', 'TM4SF19'),
 'ENSG00000270170': ('NCBP2AS2', 'NCBP2-AS2'),
 'ENSG00000169020': ('ATP5ME', 'ATP5I'),
 'ENSG00000249592': ('AC139887.2', 'RP11-440L14.1'),
 'ENSG00000196810': ('CTBP1-DT', 'CTBP1-AS2'),
 'ENSG00000109685': ('NSD2', 'WHSC1'),
 'ENSG00000206113': ('RP11-503N18.1', 'CFAP99'),
 'ENSG00000249428': ('RP11-503N18.3', 'CFAP99-1'),
 'ENSG00000273396': ('RP11-326I19.3', 'LINC01396'),
 'ENSG00000170846': ('AC093323.1', 'AC093323.3'),
 'ENSG00000251129': ('LINC02506', 'RP11-734I18.1'),
 'ENSG00000255458': ('RP11-539G18.2', 'RP11-539G18.3'),
 'ENSG00000251350': ('RP11-328N19.1', 'LVCAT1'),
 'ENSG00000250302': ('RP11-752D24.3', 'LINC01618'),
 'ENSG00000150471': ('LPHN3', 'ADGRL3'),
 'ENSG00000132465': ('IGJ', 'JCHAIN'),
 'ENSG00000269559': ('AC093677.1', 'RP11-629B11.5'),
 'ENSG00000138758': ('SEPTIN11', 'SEPT11'),
 'ENSG00000163322': ('ABRAXAS1', 'FAM175A'),
 'ENSG00000254531': ('AP001816.1', 'FLJ20021'),
 'ENSG00000246560': ('UBE2D3-AS1', 'RP11-10L12.4'),
 'ENSG00000005059': ('MCUB', 'CCDC109B'),
 'ENSG00000174749': ('FAM241A', 'C4orf32'),
 'ENSG00000249532': ('MIR302B', 'RP11-148B6.1'),
 'ENSG00000236922': ('AC092661.1', 'LINC01378'),
 'ENSG00000226757': ('AC079341.1', 'PP12613'),
 'ENSG00000151014': ('CCRN4L', 'NOCT'),
 'ENSG00000273247': ('AC097376.3', 'RP11-83A24.2'),
 'ENSG00000196951': ('RP11-425I13.3', 'SCOC-AS1'),
 'ENSG00000205301': ('RP11-542P2.1', 'MGAT4D'),
 'ENSG00000268471': ('MIR4453', 'DKFZP434I0714'),
 'ENSG00000121210': ('TMEM131L', 'KIAA0922'),
 'ENSG00000248771': ('RP11-294O2.2', 'LINC01207'),
 'ENSG00000056050': ('HPF1', 'C4orf27'),
 'ENSG00000251230': ('RP11-701P16.5', 'MIR3945HG'),
 'ENSG00000250666': ('RP11-463J17.1', 'LINC01596'),
 'ENSG00000188242': ('CTD-2228K2.5', 'PP7080'),
 'ENSG00000250490': ('CTD-2324F15.2', 'FLJ33360'),
 'ENSG00000112941': ('TENT4A', 'PAPD7'),
 'ENSG00000150756': ('ATPSCKMT', 'FAM173B'),
 'ENSG00000246016': ('RP11-1C1.7', 'LINC01513'),
 'ENSG00000248131': ('CT49', 'LINC01194'),
 'ENSG00000154153': ('RETREG1', 'FAM134B'),
 'ENSG00000272086': ('AC025181.2', 'CTD-2186M15.3'),
 'ENSG00000273294': ('RP11-1084J3.4', 'C1QTNF3-AMACR'),
 'ENSG00000197603': ('CPLANE1', 'C5orf42'),
 'ENSG00000249740': ('CTD-2127H9.1', 'OSMR-AS1'),
 'ENSG00000250722': ('SELENOP', 'SEPP1'),
 'ENSG00000215068': ('AC025171.2', 'AC025171.1'),
 'ENSG00000151881': ('TMEM267', 'C5orf28'),
 'ENSG00000039123': ('MTREX', 'SKIV2L2'),
 'ENSG00000227908': ('CTD-2031P19.3', 'FLJ31104'),
 'ENSG00000112851': ('ERBIN', 'ERBB2IP'),
 'ENSG00000249352': ('7SK', 'RP11-141O11.2'),
 'ENSG00000113163': ('CERT1', 'COL4A3BP'),
 'ENSG00000164329': ('TENT2', 'PAPD4'),
 'ENSG00000249042': ('AC008771.1', 'CTD-2015H6.3'),
 'ENSG00000251221': ('CTC-325J23.3', 'LINC01337'),
 'ENSG00000233828': ('AC008394.1', 'CTC-242N15.1'),
 'ENSG00000164199': ('GPR98', 'ADGRV1'),
 'ENSG00000236882': ('C5orf27', 'LINC01554'),
 'ENSG00000250331': ('RP11-1E3.1', 'LINC01340'),
 'ENSG00000172901': ('AQPEP', 'LVRN'),
 'ENSG00000248445': ('CTB-118N6.3', 'SEMA6A-AS1'),
 'ENSG00000155324': ('GRAMD2B', 'GRAMD3'),
 'ENSG00000196900': ('C5orf48', 'TEX43'),
 'ENSG00000230561': ('CTC-228N24.1', 'LINC01183'),
 'ENSG00000223442': ('AC004041.2', 'TH2LCRR'),
 'ENSG00000164402': ('SEPTIN8', 'SEPT8'),
 'ENSG00000249647': ('CTC-349C3.2', 'C5orf66-AS2'),
 'ENSG00000250159': ('AC106791.1', 'RP11-381K20.2'),
 'ENSG00000015479': ('MATR3', 'MATR3-1'),
 'ENSG00000249751': ('ECSCR', 'ECSCR-1'),
 'ENSG00000081791': ('DELE1', 'KIAA0141'),
 'ENSG00000249669': ('MIR143HG', 'CARMN'),
 'ENSG00000269936': ('MIR145', 'RP11-394O4.5'),
 'ENSG00000249484': ('AC091969.1', 'LINC01470'),
 'ENSG00000221886': ('C5orf54', 'ZBED8'),
 'ENSG00000253522': ('MIR146A', 'MIR3142HG'),
 'ENSG00000204767': ('INSYN2B', 'FAM196B'),
 'ENSG00000249601': ('CTB-27N1.1', 'LINC01187'),
 'ENSG00000235172': ('CTB-114C7.3', 'LINC01366'),
 'ENSG00000253686': ('CTB-43E15.3', 'LINC01484'),
 'ENSG00000254211': ('CTB-43E15.4', 'LINC01485'),
 'ENSG00000170091': ('NSG2', 'HMP19'),
 'ENSG00000204677': ('FAM153CP', 'FAM153C'),
 'ENSG00000161010': ('MRNIP', 'C5orf45'),
 'ENSG00000204628': ('RACK1', 'GNB2L1'),
 'ENSG00000164385': ('C6orf195', 'LINC01600'),
 'ENSG00000230438': ('RP11-420G6.4', 'SERPINB9P1'),
 'ENSG00000229401': ('RP1-290I10.7', 'MIR5689HG'),
 'ENSG00000079691': ('CARMIL1', 'LRRC16A'),
 'ENSG00000232040': ('SCAND3', 'ZBED9'),
 'ENSG00000225595': ('XXbac-BPG308K3.6', 'LINC01623'),
 'ENSG00000204709': ('C6orf100', 'LINC01556'),
 'ENSG00000272501': ('AL662844.4', 'XXbac-BPG299F13.17'),
 'ENSG00000250641': ('MEGT1', 'XXbac-BPG32J3.19'),
 'ENSG00000204420': ('MPIG6B', 'C6orf25'),
 'ENSG00000204387': ('SNHG32', 'C6orf48'),
 'ENSG00000204261': ('TAPSAR1', 'PSMB8-AS1'),
 'ENSG00000186577': ('SMIM29', 'C6orf1'),
 'ENSG00000196821': ('ILRUN', 'C6orf106'),
 'ENSG00000234753': ('RP11-328M4.2', 'FOXP4-AS1'),
 'ENSG00000153292': ('GPR110', 'ADGRF1'),
 'ENSG00000153294': ('GPR115', 'ADGRF4'),
 'ENSG00000146085': ('MMUT', 'MUT'),
 'ENSG00000235899': ('RP11-345L23.1', 'LINC01564'),
 'ENSG00000272316': ('AL021368.2', 'XXbac-BPGBPG55C20.2'),
 'ENSG00000227706': ('AL713998.1', 'RP11-301G19.1'),
 'ENSG00000135298': ('BAI3', 'ADGRB3'),
 'ENSG00000154079': ('C6orf57', 'SDHAF4'),
 'ENSG00000229852': ('AC019205.1', 'RP11-398K22.12'),
 'ENSG00000112773': ('TENT5A', 'FAM46A'),
 'ENSG00000224995': ('RP5-991C6.3', 'LINC01526'),
 'ENSG00000083097': ('DOP1A', 'DOPEY1'),
 'ENSG00000231776': ('RP1-90L14.1', 'LINC01611'),
 'ENSG00000228290': ('RP11-132M7.3', 'TBX18-AS1'),
 'ENSG00000272514': ('C6ORF165', 'CFAP206'),
 'ENSG00000213204': ('C6orf165', 'RP3-382I10.7'),
 'ENSG00000112297': ('CRYBG1', 'AIM1'),
 'ENSG00000130349': ('MTRES1', 'C6orf203'),
 'ENSG00000135537': ('AFG1L', 'LACE1'),
 'ENSG00000173214': ('MFSD4B', 'KIAA1919'),
 'ENSG00000153975': ('ZUP1', 'ZUFSP'),
 'ENSG00000236548': ('RP11-510H23.1', 'RNF217-AS1'),
 'ENSG00000227954': ('RP3-323P13.2', 'TARID'),
 'ENSG00000225391': ('RP11-55K22.5', 'NHEG1'),
 'ENSG00000238099': ('RP11-12A2.3', 'LINC01625'),
 'ENSG00000234147': ('AL035446.1', 'RP3-460G2.2'),
 'ENSG00000229017': ('RP11-439L18.3', 'LINC01277'),
 'ENSG00000196634': ('RP3-337D23.3', 'LUADT1'),
 'ENSG00000268592': ('RP11-244K5.8', 'RAET1E-AS1'),
 'ENSG00000224893': ('LINC02840', 'RP1-200K18.1'),
 'ENSG00000130396': ('AFDN', 'MLLT4'),
 'ENSG00000223855': ('AC147651.3', 'HRAT92'),
 'ENSG00000229043': ('AC091729.3', 'AC091729.9'),
 'ENSG00000122687': ('MRM2', 'FTSJ2'),
 'ENSG00000136243': ('NUP42', 'NUPL2'),
 'ENSG00000105928': ('GSDME', 'DFNA5'),
 'ENSG00000271122': ('AC018647.2', 'RP11-379H18.1'),
 'ENSG00000228878': ('AC007551.3', 'SEPT7-AS1'),
 'ENSG00000122545': ('SEPTIN7', 'SEPT7'),
 'ENSG00000241127': ('YAE1', 'YAE1D1'),
 'ENSG00000256646': ('PSMA2', 'RP11-111K18.1'),
 'ENSG00000228434': ('AC004951.1', 'AC004951.6'),
 'ENSG00000236078': ('AC095067.1', 'LINC01447'),
 'ENSG00000249773': ('MRPS17', 'RP11-15K19.2'),
 'ENSG00000146729': ('NIPSNAP2', 'GBAS'),
 'ENSG00000185290': ('NUPR1L', 'NUPR2'),
 'ENSG00000237310': ('AC008267.5', 'GS1-124K5.4'),
 'ENSG00000272831': ('AC027644.3', 'RP11-792A8.4'),
 'ENSG00000235475': ('RP11-166O4.5', 'LINC01372'),
 'ENSG00000071462': ('BUD23', 'WBSCR22'),
 'ENSG00000225969': ('LINC00035', 'ABHD11-AS1'),
 'ENSG00000274523': ('RCC1L', 'WBSCR16'),
 'ENSG00000146700': ('SRCRB4D', 'SSC4D'),
 'ENSG00000105792': ('C7orf63', 'CFAP69'),
 'ENSG00000188693': ('CTB-161K23.1', 'CYP51A1-AS1'),
 'ENSG00000127922': ('SEM1', 'SHFM1'),
 'ENSG00000241468': ('ATP5MF', 'ATP5J2'),
 'ENSG00000272647': ('GS1-259H13.10', 'GS1-259H13.13'),
 'ENSG00000232445': ('AC006329.1', 'RP11-132A1.4'),
 'ENSG00000267368': ('UPK3BL1', 'UPK3BL'),
 'ENSG00000241764': ('AC002467.1', 'AC002467.7'),
 'ENSG00000234520': ('AC018464.1', 'HRAT17'),
 'ENSG00000214194': ('SMIM30', 'LINC00998'),
 'ENSG00000225535': ('AC068610.3', 'LINC01393'),
 'ENSG00000225546': ('LINC02476', 'RP11-328J2.1'),
 'ENSG00000272686': ('AC006333.2', 'RP11-390E23.6'),
 'ENSG00000272899': ('RP11-309L24.9', 'RP11-309L24.4'),
 'ENSG00000272701': ('RP11-2E11.10', 'MESTIT1'),
 'ENSG00000270823': ('hsa-mir-335', 'RP11-2E11.6'),
 'ENSG00000226380': ('AC016831.1', 'AC058791.1'),
 'ENSG00000271204': ('AC016831.5', 'RP11-138A9.1'),
 'ENSG00000122783': ('CYREN', 'C7orf49'),
 'ENSG00000243317': ('STMP1', 'C7orf73'),
 'ENSG00000234352': ('hsa-mir-490', 'AC009264.1'),
 'ENSG00000164898': ('FMC1', 'C7orf55'),
 'ENSG00000269955': ('LUC7L2', 'C7orf55-LUC7L2'),
 'ENSG00000257093': ('DENND11', 'KIAA1147'),
 'ENSG00000232533': ('AC093673.1', 'AC093673.5'),

In [56]:
all_genes = {**new_genes, **all_genes}
len(all_genes)

27001

#### sciplex

In [59]:
ds_key = 'sciplex'
ds_adata = sc.read_h5ad(datasets[ds_key], backed='r')
var_df = ds_adata.var
var_df.head()

                  ensembl_id
gene_symbol
TSPAN6       ENSG00000000003
TNMD         ENSG00000000005
DPM1         ENSG00000000419
SCYL3        ENSG00000000457
C1orf112     ENSG00000000460

In [60]:
new_genes = var_df.reset_index().set_index('ensembl_id')['gene_symbol'].to_dict()
len(new_genes.keys())

110938

In [61]:
# check conflicts, these are fine to overwrite
conflicts = {k: (all_genes[k], v) for k, v in new_genes.items() if k in all_genes and all_genes[k] != v}
conflicts

{'ENSG00000002586': ('CD99', 'CD99:1'),
 'ENSG00000005379': ('BZRAP1', 'TSPOAP1'),
 'ENSG00000006015': ('REX1BD', 'C19orf60'),
 'ENSG00000010165': ('EEF1AKNMT', 'METTL13'),
 'ENSG00000011052': ('NME2', 'NME1-NME2'),
 'ENSG00000020181': ('GPR124', 'ADGRA2'),
 'ENSG00000022277': ('RTF2', 'RTFDC1'),
 'ENSG00000036549': ('AC118549.1', 'ZZZ3'),
 'ENSG00000039123': ('MTREX', 'SKIV2L2'),
 'ENSG00000040487': ('SLC66A1', 'PQLC2'),
 'ENSG00000050030': ('KIAA2022', 'NEXMIF'),
 'ENSG00000063169': ('GLTSCR1', 'BICRA'),
 'ENSG00000064489': ('MEF2BNB-MEF2B', 'BORCS8-MEF2B'),
 'ENSG00000065600': ('PACC1', 'TMEM206'),
 'ENSG00000069122': ('GPR116', 'ADGRF5'),
 'ENSG00000081791': ('DELE1', 'KIAA0141'),
 'ENSG00000082074': ('FYB', 'FYB1'),
 'ENSG00000083097': ('DOP1A', 'DOPEY1'),
 'ENSG00000083223': ('TUT7', 'ZCCHC6'),
 'ENSG00000084444': ('KIAA1467', 'FAM234B'),
 'ENSG00000086619': ('ERO1LB', 'ERO1B'),
 'ENSG00000087302': ('RTRAF', 'C14orf166'),
 'ENSG00000089101': ('C20orf26', 'CFAP61'),
 'ENSG00000093072': ('CECR1', 'ADA2'),
 'ENSG00000095397': ('DFNB31', 'WHRN'),
 'ENSG00000095932': ('C19orf77', 'SMIM24'),
 'ENSG00000099624': ('ATP5F1D', 'ATP5D'),
 'ENSG00000099625': ('C19orf26', 'CBARP'),
 'ENSG00000100101': ('NOL12', 'Z83844.1'),
 'ENSG00000100218': ('RTDR1', 'RSPH14'),
 'ENSG00000100647': ('KIAA0247', 'SUSD6'),
 'ENSG00000100890': ('PRORP', 'KIAA0391'),
 'ENSG00000101084': ('RAB5IF', 'C20orf24'),
 'ENSG00000101349': ('PAK7', 'PAK5'),
 'ENSG00000102445': ('KIAA0226L', 'RUBCNL'),
 'ENSG00000103245': ('CIAO3', 'NARFL'),
 'ENSG00000103254': ('ANTKMT', 'FAM173A'),
 'ENSG00000103544': ('VPS35L', 'C16orf62'),
 'ENSG00000103888': ('KIAA1199', 'CEMIP'),
 'ENSG00000104827': ('CGB', 'CGB3'),
 'ENSG00000104964': ('TLE5', 'AES'),
 'ENSG00000105248': ('YJU2', 'CCDC94'),
 'ENSG00000105792': ('C7orf63', 'CFAP69'),
 'ENSG00000105928': ('GSDME', 'DFNA5'),
 'ENSG00000106125': ('FAM188B', 'MINDY4'),
 'ENSG00000108021': ('TASOR2', 'FAM208B'),
 'ENSG00000110400': ('PVRL1', 'NECTIN1'),
 'ENSG00000110955': ('ATP5F1B', 'ATP5B'),
 'ENSG00000111452': ('GPR133', 'ADGRD1'),
 'ENSG00000111780': ('AL021546.6', 'AL021546.1'),
 'ENSG00000111913': ('FAM65B', 'RIPOR2'),
 'ENSG00000112624': ('GLTSCR1L', 'BICRAL'),
 'ENSG00000112773': ('TENT5A', 'FAM46A'),
 'ENSG00000112941': ('TENT4A', 'PAPD7'),
 'ENSG00000113163': ('CERT1', 'COL4A3BP'),
 'ENSG00000115934': ('RP11-153K16.2', 'AC087235.1'),
 'ENSG00000116459': ('ATP5PB', 'ATP5F1'),
 'ENSG00000116747': ('RO60', 'TROVE2'),
 'ENSG00000116883': ('RP11-268J15.5', 'AL591845.1'),
 'ENSG00000117597': ('UTP25', 'DIEXF'),
 'ENSG00000118523': ('CCN2', 'CTGF'),
 'ENSG00000118600': ('RXYLT1', 'TMEM5'),
 'ENSG00000119328': ('ABITRAM', 'FAM206A'),
 'ENSG00000119636': ('CCDC176', 'BBOF1'),
 'ENSG00000119979': ('DENND10', 'FAM45A'),
 'ENSG00000120029': ('ARMH3', 'C10orf76'),
 'ENSG00000120051': ('CCDC147', 'CFAP58'),
 'ENSG00000120664': ('SPG20OS', 'SPG20-AS1'),
 'ENSG00000121274': ('TENT4B', 'PAPD5'),
 'ENSG00000121388': ('RP11-408E5.4', 'AL139327.1'),
 'ENSG00000121753': ('BAI2', 'ADGRB2'),
 'ENSG00000121933': ('ADORA3', 'TMIGD3'),
 'ENSG00000122376': ('SHLD2', 'FAM35A'),
 'ENSG00000122378': ('PRXL2A', 'FAM213A'),
 'ENSG00000122490': ('SLC66A2', 'PQLC1'),
 'ENSG00000122545': ('SEPTIN7', 'SEPT7'),
 'ENSG00000122733': ('KIAA1045', 'PHF24'),
 'ENSG00000122783': ('CYREN', 'C7orf49'),
 'ENSG00000123427': ('METTL21B', 'EEF1AKMT3'),
 'ENSG00000124172': ('ATP5F1E', 'ATP5E'),
 'ENSG00000124333': ('VAMP7', 'VAMP7:1'),
 'ENSG00000124334': ('IL9R', 'IL9R:1'),
 'ENSG00000124593': ('PRICKLE4', 'AL365205.1'),
 'ENSG00000124835': ('AC105760.3', 'AC105760.1'),
 'ENSG00000124915': ('RP11-467L20.10', 'DKFZP434K028'),
 'ENSG00000125354': ('SEPTIN6', 'SEPT6'),
 'ENSG00000125375': ('DMAC2L', 'ATP5S'),
 'ENSG00000125531': ('C20orf195', 'FNDC11'),
 'ENSG00000126005': ('MMP24OS', 'MMP24-AS1'),
 'ENSG00000126950': ('TMEM35', 'TMEM35A'),
 'ENSG00000127507': ('EMR2', 'ADGRE2'),
 'ENSG00000130038': ('EFCAB4B', 'CRACR2A'),
 'ENSG00000130173': ('C19orf80', 'ANGPTL8'),
 'ENSG00000130349': ('MTRES1', 'C6orf203'),
 'ENSG00000130770': ('ATP5IF1', 'ATPIF1'),
 'ENSG00000130813': ('SHFL', 'C19orf66'),
 'ENSG00000131152': ('RP11-178L8.4', 'AC010531.1'),
 'ENSG00000131484': ('RP11-798G7.5', 'AC091132.1'),
 'ENSG00000132465': ('IGJ', 'JCHAIN'),
 'ENSG00000132680': ('KHDC4', 'KIAA0907'),
 'ENSG00000132749': ('MTL5', 'TESMIN'),
 'ENSG00000132832': ('RP11-445H22.3', 'LINC01260'),
 'ENSG00000133321': ('PLAAT4', 'RARRES3'),
 'ENSG00000133424': ('LARGE', 'LARGE1'),
 'ENSG00000133943': ('DGLUCY', 'C14orf159'),
 'ENSG00000134444': ('RELCH', 'KIAA1468'),
 'ENSG00000134452': ('FBH1', 'FBXO18'),
 'ENSG00000134548': ('C12orf39', 'SPX'),
 'ENSG00000134744': ('TUT4', 'ZCCHC11'),
 'ENSG00000134901': ('POGLUT2', 'KDELC1'),
 'ENSG00000135048': ('CEMIP2', 'TMEM2'),
 'ENSG00000135127': ('CCDC64', 'BICDL1'),
 'ENSG00000135298': ('BAI3', 'ADGRB3'),
 'ENSG00000135390': ('ATP5MC2', 'ATP5G2'),
 'ENSG00000135697': ('BCMO1', 'BCO1'),
 'ENSG00000135747': ('ZNF670', 'ZNF670-ZNF695'),
 'ENSG00000135749': ('PCNXL2', 'PCNX2'),
 'ENSG00000135842': ('NIBAN1', 'FAM129A'),
 'ENSG00000136110': ('LECT1', 'CNMD'),
 'ENSG00000136243': ('NUP42', 'NUPL2'),
 'ENSG00000136813': ('ECPAS', 'KIAA0368'),
 'ENSG00000136830': ('NIBAN2', 'FAM129B'),
 'ENSG00000136999': ('CCN3', 'NOV'),
 'ENSG00000137691': ('CFAP300', 'C11orf70'),
 'ENSG00000138111': ('TMEM180', 'MFSD13A'),
 'ENSG00000138434': ('ITPRID2', 'SSFA2'),
 'ENSG00000138463': ('SLC49A4', 'DIRC2'),
 'ENSG00000138758': ('SEPTIN11', 'SEPT11'),
 'ENSG00000139146': ('SINHCAF', 'FAM60A'),
 'ENSG00000139160': ('METTL20', 'ETFBKMT'),
 'ENSG00000140488': ('CELF6-1', 'CELF6'),
 'ENSG00000140950': ('MEAK7', 'TLDC1'),
 'ENSG00000141391': ('SLMO1', 'PRELID3A'),
 'ENSG00000141441': ('GAREM', 'GAREM1'),
 'ENSG00000141577': ('AZI1', 'CEP131'),
 'ENSG00000141854': ('hsa-mir-1199', 'MISP3'),
 'ENSG00000141979': ('CTD-3222D19.2', 'AC008764.1'),
 'ENSG00000142102': ('ATHL1', 'PGGHG'),
 'ENSG00000142197': ('DOP1B', 'DOPEY2'),
 'ENSG00000142396': ('ERVK3-1', 'AC020915.1'),
 'ENSG00000142513': ('ACPT', 'ACP4'),
 'ENSG00000142539': ('CTD-2545M3.6', 'AC020909.1'),
 'ENSG00000142609': ('C1orf222', 'CFAP74'),
 'ENSG00000142871': ('CCN1', 'CYR61'),
 'ENSG00000142920': ('ADC', 'AZIN2'),
 'ENSG00000143207': ('COP1', 'RFWD2'),
 'ENSG00000143217': ('PVRL4', 'NECTIN4'),
 'ENSG00000143409': ('FAM63A', 'MINDY1'),
 'ENSG00000143674': ('MLK4', 'MAP3K21'),
 'ENSG00000144785': ('RP11-977G19.10', 'AC073896.1'),
 'ENSG00000145107': ('TM4SF19-1', 'TM4SF19'),
 'ENSG00000146085': ('MMUT', 'MUT'),
 'ENSG00000146700': ('SRCRB4D', 'SSC4D'),
 'ENSG00000147174': ('ACRC', 'GCNA'),
 'ENSG00000148120': ('AOPEP', 'C9orf3'),
 'ENSG00000149474': ('CSRP2BP', 'KAT14'),
 'ENSG00000149531': ('FRG1B', 'FRG1BP'),
 'ENSG00000149716': ('LTO1', 'ORAOV1'),
 'ENSG00000150471': ('LPHN3', 'ADGRL3'),
 'ENSG00000150527': ('MIA2', 'CTAGE5'),
 'ENSG00000150756': ('ATPSCKMT', 'FAM173B'),
 'ENSG00000150776': ('NKAPD1', 'C11orf57'),
 'ENSG00000151014': ('CCRN4L', 'NOCT'),
 'ENSG00000152193': ('OBI1', 'RNF219'),
 'ENSG00000152234': ('ATP5F1A', 'ATP5A1'),
 'ENSG00000152936': ('IFLTD1', 'LMNTD1'),
 'ENSG00000153292': ('GPR110', 'ADGRF1'),
 'ENSG00000153294': ('GPR115', 'ADGRF4'),
 'ENSG00000153975': ('ZUP1', 'ZUFSP'),
 'ENSG00000154079': ('C6orf57', 'SDHAF4'),
 'ENSG00000154511': ('DIPK1A', 'FAM69A'),
 'ENSG00000154518': ('ATP5MC3', 'ATP5G3'),
 'ENSG00000154723': ('ATP5PF', 'ATP5J'),
 'ENSG00000155099': ('PIP4P2', 'TMEM55A'),
 'ENSG00000155754': ('ALS2CR11', 'C2CD6'),
 'ENSG00000155893': ('ACPL2', 'PXYLP1'),
 'ENSG00000156042': ('TTC18', 'CFAP70'),
 'ENSG00000156206': ('C15orf26', 'CFAP161'),
 'ENSG00000156411': ('ATP5MPL', 'C14orf2'),
 'ENSG00000157181': ('ODR4', 'C1orf27'),
 'ENSG00000157306': ('RP11-66N24.4', 'ZFHX2-AS1'),
 'ENSG00000157538': ('VPS26C', 'DSCR3'),
 'ENSG00000157833': ('GAREML', 'GAREM2'),
 'ENSG00000157870': ('PRXL2B', 'FAM213B'),
 'ENSG00000158122': ('PRXL2C', 'AAED1'),
 'ENSG00000158428': ('C2orf62', 'CATIP'),
 'ENSG00000159079': ('CFAP298', 'C21orf59'),
 'ENSG00000159199': ('ATP5MC1', 'ATP5G1'),
 'ENSG00000159208': ('C1orf51', 'CIART'),
 'ENSG00000159239': ('C2orf81', 'AC005041.1'),
 'ENSG00000159618': ('GPR114', 'ADGRG5'),
 'ENSG00000159625': ('CCDC135', 'DRC7'),
 'ENSG00000159753': ('RLTPR', 'CARMIL2'),
 'ENSG00000160226': ('CFAP410', 'C21orf2'),
 'ENSG00000160401': ('C9orf117', 'CFAP157'),
 'ENSG00000160539': ('PPAPDC3', 'PLPP7'),
 'ENSG00000160593': ('AMICA1', 'JAML'),
 'ENSG00000160953': ('PWWP3A', 'MUM1'),
 'ENSG00000161103': ('AC008132.13', 'AC008132.1'),
 'ENSG00000161992': ('C16orf11', 'PRR35'),
 'ENSG00000162062': ('TEDC2', 'C16orf59'),
 'ENSG00000162069': ('CCDC64B', 'BICDL2'),
 'ENSG00000162194': ('C11orf48', 'LBHD1'),
 'ENSG00000162384': ('CZIB', 'C1orf123'),
 'ENSG00000162825': ('NBPF8', 'NBPF20'),
 'ENSG00000162894': ('FAIM3', 'FCMR'),
 'ENSG00000162913': ('C1orf145', 'OBSCN-AS1'),
 'ENSG00000162976': ('SLC66A3', 'PQLC3'),
 'ENSG00000163362': ('C1orf106', 'INAVA'),
 'ENSG00000163507': ('CIP2A', 'KIAA1524'),
 'ENSG00000163617': ('KIAA1407', 'CCDC191'),
 'ENSG00000163885': ('CCDC37', 'CFAP100'),
 'ENSG00000163915': ('C3orf65', 'IGF2BP2-AS1'),
 'ENSG00000163946': ('TASOR', 'FAM208A'),
 'ENSG00000163975': ('MFI2', 'MELTF'),
 'ENSG00000164199': ('GPR98', 'ADGRV1'),
 'ENSG00000164329': ('TENT2', 'PAPD4'),
 'ENSG00000164385': ('C6orf195', 'LINC01600'),
 'ENSG00000164402': ('SEPTIN8', 'SEPT8'),
 'ENSG00000164556': ('FAM183B', 'FAM183BP'),
 'ENSG00000164603': ('C7orf60', 'BMT2'),
 'ENSG00000165164': ('CXorf22', 'CFAP47'),
 'ENSG00000165171': ('WBSCR27', 'METTL27'),
 'ENSG00000165197': ('FIGF', 'VEGFD'),
 'ENSG00000165325': ('CCDC67', 'DEUP1'),
 'ENSG00000165359': ('DDX26B', 'INTS6L'),
 'ENSG00000165629': ('ATP5F1C', 'ATP5C1'),
 'ENSG00000165689': ('ENTR1', 'SDCCAG3'),
 'ENSG00000165716': ('DIPK1B', 'FAM69B'),
 'ENSG00000165757': ('KIAA1462', 'JCAD'),
 'ENSG00000165782': ('PIP4P1', 'TMEM55B'),
 'ENSG00000165905': ('GYLTL1B', 'LARGE2'),
 'ENSG00000166595': ('CIAO2B', 'FAM96B'),
 'ENSG00000166596': ('WDR16', 'CFAP52'),
 'ENSG00000166780': ('BMERB1', 'C16orf45'),
 'ENSG00000166797': ('CIAO2A', 'FAM96A'),
 'ENSG00000167014': ('C15orf43', 'TERB2'),
 'ENSG00000167046': ('RP11-93B14.6', 'AL357033.1'),
 'ENSG00000167283': ('ATP5MG', 'ATP5L'),
 'ENSG00000167302': ('ENTHD2', 'TEPSIN'),
 'ENSG00000167393': ('PPP2R3B', 'PPP2R3B:1'),
 'ENSG00000167524': ('RSKR', 'SGK494'),
 'ENSG00000167695': ('TLCD3A', 'FAM57A'),
 'ENSG00000167774': ('NDUFA7', 'AC010323.1'),
 'ENSG00000167807': ('CTD-2369P2.10', 'AC011511.1'),
 'ENSG00000167863': ('ATP5PD', 'ATP5H'),
 'ENSG00000167912': ('RP11-25K19.1', 'AC090152.1'),
 'ENSG00000168005': ('SPINDOC', 'C11orf84'),
 'ENSG00000168070': ('C11orf85', 'MAJIN'),
 'ENSG00000168385': ('SEPTIN2', 'SEPT2'),
 'ENSG00000168497': ('SDPR', 'CAVIN2'),
 'ENSG00000168746': ('C20orf62', 'LINC01620'),
 'ENSG00000168824': ('NSG1', 'HGNC:18790'),
 'ENSG00000168939': ('SPRY3', 'SPRY3:1'),
 'ENSG00000169020': ('ATP5ME', 'ATP5I'),
 'ENSG00000169084': ('DHRSX', 'DHRSX:1'),
 'ENSG00000169093': ('ASMTL', 'ASMTL:1'),
 'ENSG00000169100': ('SLC25A6', 'SLC25A6:1'),
 'ENSG00000169203': ('RP11-231C14.4', 'NPIPB12'),
 'ENSG00000169612': ('RAMAC', 'FAM103A1'),
 'ENSG00000169660': ('HEXD', 'HEXDC'),
 'ENSG00000169758': ('C15orf27', 'TMEM266'),
 'ENSG00000170091': ('NSG2', 'HGNC:24955'),
 'ENSG00000170161': ('RP11-262H14.4', 'AL512625.1'),
 'ENSG00000170379': ('FAM115C', 'TCAF2'),
 'ENSG00000170681': ('MURC', 'CAVIN4'),
 'ENSG00000170955': ('PRKCDBP', 'CAVIN3'),
 'ENSG00000171097': ('CCBL1', 'KYAT1'),
 'ENSG00000171224': ('FAM241B', 'C10orf35'),
 'ENSG00000171695': ('C20orf201', 'LKAAEAR1'),
 'ENSG00000171722': ('C1orf111', 'SPATA46'),
 'ENSG00000171811': ('TTC40', 'CFAP46'),
 'ENSG00000171962': ('LRRC48', 'DRC3'),
 'ENSG00000171984': ('SHLD1', 'C20orf196'),
 'ENSG00000172361': ('CCDC11', 'CFAP53'),
 'ENSG00000172901': ('AQPEP', 'LVRN'),
 'ENSG00000173124': ('C10orf129', 'ACSM6'),
 'ENSG00000173436': ('MICOS10', 'MINOS1'),
 'ENSG00000173465': ('ZNRD2', 'SSSCA1'),
 'ENSG00000173567': ('GPR113', 'ADGRF3'),
 'ENSG00000173681': ('CXorf23', 'BCLAF3'),
 'ENSG00000173862': ('RP11-89N17.1', 'AC008080.1'),
 'ENSG00000173915': ('ATP5MD', 'USMG5'),
 'ENSG00000174145': ('KIAA1239', 'NWD2'),
 'ENSG00000174171': ('RP11-23P13.6', 'AC020659.1'),
 'ENSG00000174514': ('MFSD4', 'MFSD4A'),
 'ENSG00000174718': ('RESF1', 'KIAA1551'),
 'ENSG00000174749': ('FAM241A', 'C4orf32'),
 'ENSG00000174837': ('EMR1', 'ADGRE1'),
 'ENSG00000174899': ('SLC66A1L', 'PQLC2L'),
 'ENSG00000174917': ('MICOS13', 'C19orf70'),
 'ENSG00000175061': ('SNHG29', 'LRRC75A-AS1'),
 'ENSG00000175318': ('GRAMD2', 'GRAMD2A'),
 'ENSG00000175604': ('RP11-276H1.3', 'AC007601.1'),
 'ENSG00000175701': ('MTLN', 'LINC00116'),
 'ENSG00000175707': ('C1orf172', 'KDF1'),
 'ENSG00000175773': ('RP11-121M22.1', 'AP002986.1'),
 'ENSG00000175877': ('WBSCR28', 'TMEM270'),
 'ENSG00000175967': ('RP11-544L8__B.4', 'FO393415.1'),
 'ENSG00000176076': ('KCNE1L', 'KCNE5'),
 'ENSG00000176092': ('AIM1L', 'CRYBG2'),
 'ENSG00000176320': ('RP11-404O13.5', 'AL138899.1'),
 'ENSG00000176349': ('AC110781.3', 'AC104129.1'),
 'ENSG00000176485': ('PLAAT3', 'PLA2G16'),
 'ENSG00000176731': ('RBIS', 'C8orf59'),
 'ENSG00000176868': ('RP11-334J6.7', 'AL358781.1'),
 'ENSG00000176984': ('AP000679.2', 'AP000679.1'),
 'ENSG00000177234': ('C10orf85', 'LINC01561'),
 'ENSG00000177340': ('AC024940.1', 'FLJ13224'),
 'ENSG00000177359': ('OVOS2', 'AC024940.1'),
 'ENSG00000177406': ('RP11-218M22.1', 'AC021054.1'),
 'ENSG00000177459': ('C8orf47', 'ERICH5'),
 'ENSG00000177553': ('RP11-56N19.5', 'AL953897.1'),
 'ENSG00000177595': ('PIDD', 'PIDD1'),
 'ENSG00000177602': ('GSG2', 'HASPIN'),
 'ENSG00000177685': ('EFCAB4A', 'CRACR2B'),
 'ENSG00000177699': ('RP11-16K12.1', 'AC011944.1'),
 'ENSG00000177822': ('AC108142.1', 'AC098864.1'),
 'ENSG00000177875': ('C12orf68', 'CCDC184'),
 'ENSG00000178026': ('FAM211B', 'LRRC75B'),
 'ENSG00000178107': ('RP11-998D10.4', 'AL161668.1'),
 'ENSG00000178193': ('RP4-682C21.5', 'AL357314.1'),
 'ENSG00000178202': ('POGLUT3', 'KDELC2'),
 'ENSG00000178248': ('AP000345.1', 'LINC01658'),
 'ENSG00000178386': ('ZNF223-1', 'ZNF223'),
 'ENSG00000178605': ('GTPBP6', 'GTPBP6:1'),
 'ENSG00000178636': ('RP11-455G16.1', 'AC092656.1'),
 'ENSG00000178734': ('C13orf45', 'LMO7DN'),
 'ENSG00000178752': ('FAM132B', 'ERFE'),
 'ENSG00000178882': ('FAM101A', 'RFLNA'),
 'ENSG00000178927': ('CYBC1', 'C17orf62'),
 'ENSG00000178947': ('LINC00086', 'SMIM10L2A'),
 'ENSG00000178965': ('C1orf173', 'ERICH3'),
 'ENSG00000179240': ('GVQW3', 'AP002360.1'),
 'ENSG00000179253': ('RP11-429E11.3', 'AL162457.1'),
 'ENSG00000179397': ('C1orf101', 'CATSPERE'),
 'ENSG00000179428': ('AC073072.5', 'AC073072.1'),
 'ENSG00000179447': ('RP5-1027G4.3', 'AL049647.1'),
 'ENSG00000179452': ('RP11-380B22.1', 'LINC01699'),
 'ENSG00000179523': ('EIF3J-DT', 'EIF3J-AS1'),
 'ENSG00000179698': ('KIAA1875', 'WDR97'),
 'ENSG00000179743': ('AL450998.2', 'FLJ37453'),
 'ENSG00000179840': ('C1orf200', 'PIK3CD-AS1'),
 'ENSG00000179859': ('AC025335.1', 'AC104581.1'),
 'ENSG00000180096': ('SEPTIN1', 'SEPT1'),
 'ENSG00000180279': ('CTD-2568A17.5', 'LINC01869'),
 'ENSG00000180336': ('C17orf104', 'MEIOC'),
 'ENSG00000180448': ('HMHA1', 'ARHGAP45'),
 'ENSG00000180458': ('CTD-3064H18.4', 'AC022148.1'),
 'ENSG00000180574': ('EIF2S3L', 'AC068775.1'),
 'ENSG00000180712': ('RP11-290F5.2', 'LINC02363'),
 'ENSG00000180869': ('C1orf180', 'LINC01555'),
 'ENSG00000180953': ('AC015871.1', 'ST20'),
 'ENSG00000181097': ('RP11-429J17.2', 'AC105219.1'),
 'ENSG00000181123': ('RP4-539M6.14', 'AC004832.1'),
 'ENSG00000181264': ('TLCD5', 'TMEM136'),
 'ENSG00000181378': ('CCDC108', 'CFAP65'),
 'ENSG00000181744': ('DIPK2A', 'C3orf58'),
 'ENSG00000181790': ('BAI1', 'ADGRB1'),
 'ENSG00000181908': ('AP003774.4', 'AP003774.1'),
 'ENSG00000182021': ('RP11-381O7.3', 'AL591379.1'),
 'ENSG00000182057': ('Z83851.3', 'OGFRP1'),
 'ENSG00000182093': ('GET1', 'WRB'),
 'ENSG00000182109': ('RP11-69E11.4', 'AL365277.1'),
 'ENSG00000182162': ('P2RY8', 'P2RY8:1'),
 'ENSG00000182257': ('C22orf26', 'PRR34'),
 'ENSG00000182329': ('AC079354.1', 'KIAA2012'),
 'ENSG00000182376': ('RP5-1142A6.8', 'AC138028.1'),
 'ENSG00000182378': ('PLCXD1', 'PLCXD1:1'),
 'ENSG00000182873': ('RP11-181G12.2', 'PRKCZ-AS1'),
 'ENSG00000182885': ('GPR97', 'ADGRG3'),
 'ENSG00000182912': ('C21orf90', 'TSPEAR-AS2'),
 'ENSG00000183019': ('C19orf59', 'MCEMP1'),
 'ENSG00000183154': ('RP11-863K10.7', 'AC138356.1'),
 'ENSG00000183248': ('CTD-3193O13.9', 'PRR36'),
 'ENSG00000183250': ('C21orf67', 'LINC01547'),
 'ENSG00000183292': ('AC140481.2', 'TISP43'),
 'ENSG00000183307': ('CECR6', 'TMEM121B'),
 'ENSG00000183308': ('AC005037.3', 'AC005037.1'),
 'ENSG00000183760': ('PAPL', 'ACP7'),
 'ENSG00000183791': ('TCEB3C', 'ELOA3'),
 'ENSG00000183822': ('CTA-833B7.2', 'NCF4-AS1'),
 'ENSG00000183889': ('NPIPA7', 'AC138969.1'),
 'ENSG00000184068': ('RP5-821D11.7', 'AL021453.1'),
 'ENSG00000184115': ('RP13-1039J1.2', 'AC112229.1'),
 'ENSG00000184163': ('FAM132A', 'C1QTNF12'),
 'ENSG00000184385': ('C21orf128', 'UMODL1-AS1'),
 'ENSG00000184441': ('AP001062.7', 'AP001062.1'),
 'ENSG00000184608': ('C8orf12', 'FAM167A-AS1'),
 'ENSG00000184640': ('SEPTIN9', 'SEPT9'),
 'ENSG00000184702': ('SEPTIN5', 'SEPT5'),
 'ENSG00000184774': ('RP11-480I12.4', 'MGAT4EP'),
 'ENSG00000184906': ('AC129778.2', 'AMYH02020865.1'),
 'ENSG00000185065': ('AC000068.5', 'AC000068.1'),
 'ENSG00000185203': ('WASIR1', 'WASIR1:1'),
 'ENSG00000185290': ('NUPR1L', 'NUPR2'),
 'ENSG00000185291': ('IL3RA', 'IL3RA:1'),
 'ENSG00000185345': ('PARK2', 'PRKN'),
 'ENSG00000185347': ('TEDC1', 'C14orf80'),
 'ENSG00000185495': ('RP11-504P24.4', 'AC138393.1'),
 'ENSG00000185522': ('C11orf35', 'LMNTD2'),
 'ENSG00000185523': ('C1orf227', 'SPATA45'),
 'ENSG00000185614': ('INKA1', 'FAM212A'),
 'ENSG00000185716': ('MOSMO', 'C16orf52'),
 'ENSG00000185837': ('CECR5-AS1', 'HDHD5-AS1'),
 'ENSG00000185860': ('C1orf110', 'CCDC190'),
 'ENSG00000185960': ('SHOX', 'SHOX:1'),
 'ENSG00000186019': ('AC084219.4', 'AC021092.1'),
 'ENSG00000186235': ('LINC02610', 'AC016757.1'),
 'ENSG00000186260': ('MRTFB', 'MKL2'),
 'ENSG00000186522': ('SEPTIN10', 'SEPT10'),
 'ENSG00000186648': ('LRRC16B', 'CARMIL3'),
 'ENSG00000186710': ('CCDC42B', 'CFAP73'),
 'ENSG00000186838': ('SELV', 'SELENOV'),
 'ENSG00000186960': ('C14orf23', 'LINC01551'),
 'ENSG00000187185': ('CTD-2600O9.1', 'AC092118.1'),
 'ENSG00000187186': ('RP11-195F19.5', 'AL162231.1'),
 'ENSG00000187516': ('CXorf27', 'HYPM'),
 'ENSG00000187642': ('C1orf170', 'PERM1'),
 'ENSG00000187695': ('RP11-723O4.6', 'AC112484.1'),
 'ENSG00000187889': ('C1orf168', 'FYB2'),
 'ENSG00000187905': ('AC002472.13', 'LRRC74B'),
 'ENSG00000187979': ('AC008079.9', 'AC008079.1'),
 'ENSG00000188004': ('C1orf204', 'SNHG28'),
 'ENSG00000188011': ('CXXC11', 'RTP5'),
 'ENSG00000188242': ('CTD-2228K2.5', 'PP7080'),
 'ENSG00000188280': ('FAM230A', 'AC007731.1'),
 'ENSG00000188365': ('AC092171.2', 'AC092171.1'),
 'ENSG00000188523': ('C9orf171', 'CFAP77'),
 'ENSG00000188549': ('CCDC9B', 'C15orf52'),
 'ENSG00000188596': ('C12orf55', 'CFAP54'),
 'ENSG00000188659': ('FAM154B', 'SAXO2'),
 'ENSG00000188693': ('CTB-161K23.1', 'CYP51A1-AS1'),
 'ENSG00000188897': ('CTD-3088G3.8', 'AC099489.1'),
 'ENSG00000188931': ('C1orf192', 'CFAP126'),
 'ENSG00000189195': ('BTBD8', 'AC104836.1'),
 'ENSG00000189269': ('C22orf43', 'DRICH1'),
 'ENSG00000189275': ('AL450307.1', 'LINC01164'),
 'ENSG00000189292': ('FAM150B', 'ALKAL2'),
 'ENSG00000189316': ('RP11-797H7.5', 'AC073349.1'),
 'ENSG00000189332': ('RP11-113D6.10', 'AC090099.1'),
 'ENSG00000189350': ('FAM179A', 'TOGARAM2'),
 'ENSG00000189362': ('TMEM194B', 'NEMP2'),
 'ENSG00000196096': ('AC079610.2', 'AC079610.1'),
 'ENSG00000196118': ('C16orf93', 'CCDC189'),
 'ENSG00000196295': ('GARS-DT', 'AC005154.1'),
 'ENSG00000196421': ('LINC00176', 'C20orf204'),
 'ENSG00000196433': ('ASMT', 'ASMT:1'),
 'ENSG00000196544': ('C17orf59', 'BORCS6'),
 'ENSG00000196566': ('RP11-57C13.3', 'AL138767.1'),
 'ENSG00000196588': ('MRTFA', 'MKL1'),
 'ENSG00000196634': ('RP3-337D23.3', 'LUADT1'),

In [62]:
all_genes = {**new_genes, **all_genes}
len(all_genes)

111820